// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-client/models"
)

// CheckOrderStatusReader is a Reader for the CheckOrderStatus structure.
type CheckOrderStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckOrderStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckOrderStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 302:
		result := NewCheckOrderStatusFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewCheckOrderStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCheckOrderStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCheckOrderStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewCheckOrderStatusServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /brigade/status/{order_id}] checkOrderStatus", response, response.Code())
	}
}

// NewCheckOrderStatusOK creates a CheckOrderStatusOK with default headers values
func NewCheckOrderStatusOK() *CheckOrderStatusOK {
	return &CheckOrderStatusOK{}
}

/*
CheckOrderStatusOK describes a response with status code 200, with default header values.

OK
*/
type CheckOrderStatusOK struct {

	/* Retry after seconds

	   Format: int32
	*/
	RetryAfter string

	Payload *models.OrderStatus
}

// IsSuccess returns true when this check order status o k response has a 2xx status code
func (o *CheckOrderStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check order status o k response has a 3xx status code
func (o *CheckOrderStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check order status o k response has a 4xx status code
func (o *CheckOrderStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check order status o k response has a 5xx status code
func (o *CheckOrderStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check order status o k response a status code equal to that given
func (o *CheckOrderStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check order status o k response
func (o *CheckOrderStatusOK) Code() int {
	return 200
}

func (o *CheckOrderStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusOK %s", 200, payload)
}

func (o *CheckOrderStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusOK %s", 200, payload)
}

func (o *CheckOrderStatusOK) GetPayload() *models.OrderStatus {
	return o.Payload
}

func (o *CheckOrderStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		o.RetryAfter = hdrRetryAfter
	}

	o.Payload = new(models.OrderStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckOrderStatusFound creates a CheckOrderStatusFound with default headers values
func NewCheckOrderStatusFound() *CheckOrderStatusFound {
	return &CheckOrderStatusFound{}
}

/*
CheckOrderStatusFound describes a response with status code 302, with default header values.

Found
*/
type CheckOrderStatusFound struct {

	/* Location
	 */
	Location string

	Payload *models.OrderStatus
}

// IsSuccess returns true when this check order status found response has a 2xx status code
func (o *CheckOrderStatusFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check order status found response has a 3xx status code
func (o *CheckOrderStatusFound) IsRedirect() bool {
	return true
}

// IsClientError returns true when this check order status found response has a 4xx status code
func (o *CheckOrderStatusFound) IsClientError() bool {
	return false
}

// IsServerError returns true when this check order status found response has a 5xx status code
func (o *CheckOrderStatusFound) IsServerError() bool {
	return false
}

// IsCode returns true when this check order status found response a status code equal to that given
func (o *CheckOrderStatusFound) IsCode(code int) bool {
	return code == 302
}

// Code gets the status code for the check order status found response
func (o *CheckOrderStatusFound) Code() int {
	return 302
}

func (o *CheckOrderStatusFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusFound %s", 302, payload)
}

func (o *CheckOrderStatusFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusFound %s", 302, payload)
}

func (o *CheckOrderStatusFound) GetPayload() *models.OrderStatus {
	return o.Payload
}

func (o *CheckOrderStatusFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	o.Payload = new(models.OrderStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckOrderStatusBadRequest creates a CheckOrderStatusBadRequest with default headers values
func NewCheckOrderStatusBadRequest() *CheckOrderStatusBadRequest {
	return &CheckOrderStatusBadRequest{}
}

/*
CheckOrderStatusBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CheckOrderStatusBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this check order status bad request response has a 2xx status code
func (o *CheckOrderStatusBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check order status bad request response has a 3xx status code
func (o *CheckOrderStatusBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check order status bad request response has a 4xx status code
func (o *CheckOrderStatusBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this check order status bad request response has a 5xx status code
func (o *CheckOrderStatusBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this check order status bad request response a status code equal to that given
func (o *CheckOrderStatusBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the check order status bad request response
func (o *CheckOrderStatusBadRequest) Code() int {
	return 400
}

func (o *CheckOrderStatusBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusBadRequest %s", 400, payload)
}

func (o *CheckOrderStatusBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusBadRequest %s", 400, payload)
}

func (o *CheckOrderStatusBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CheckOrderStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckOrderStatusUnauthorized creates a CheckOrderStatusUnauthorized with default headers values
func NewCheckOrderStatusUnauthorized() *CheckOrderStatusUnauthorized {
	return &CheckOrderStatusUnauthorized{}
}

/*
CheckOrderStatusUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CheckOrderStatusUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this check order status unauthorized response has a 2xx status code
func (o *CheckOrderStatusUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check order status unauthorized response has a 3xx status code
func (o *CheckOrderStatusUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check order status unauthorized response has a 4xx status code
func (o *CheckOrderStatusUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this check order status unauthorized response has a 5xx status code
func (o *CheckOrderStatusUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this check order status unauthorized response a status code equal to that given
func (o *CheckOrderStatusUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the check order status unauthorized response
func (o *CheckOrderStatusUnauthorized) Code() int {
	return 401
}

func (o *CheckOrderStatusUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusUnauthorized %s", 401, payload)
}

func (o *CheckOrderStatusUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusUnauthorized %s", 401, payload)
}

func (o *CheckOrderStatusUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CheckOrderStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckOrderStatusInternalServerError creates a CheckOrderStatusInternalServerError with default headers values
func NewCheckOrderStatusInternalServerError() *CheckOrderStatusInternalServerError {
	return &CheckOrderStatusInternalServerError{}
}

/*
CheckOrderStatusInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CheckOrderStatusInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this check order status internal server error response has a 2xx status code
func (o *CheckOrderStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check order status internal server error response has a 3xx status code
func (o *CheckOrderStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check order status internal server error response has a 4xx status code
func (o *CheckOrderStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this check order status internal server error response has a 5xx status code
func (o *CheckOrderStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this check order status internal server error response a status code equal to that given
func (o *CheckOrderStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the check order status internal server error response
func (o *CheckOrderStatusInternalServerError) Code() int {
	return 500
}

func (o *CheckOrderStatusInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusInternalServerError %s", 500, payload)
}

func (o *CheckOrderStatusInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusInternalServerError %s", 500, payload)
}

func (o *CheckOrderStatusInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CheckOrderStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckOrderStatusServiceUnavailable creates a CheckOrderStatusServiceUnavailable with default headers values
func NewCheckOrderStatusServiceUnavailable() *CheckOrderStatusServiceUnavailable {
	return &CheckOrderStatusServiceUnavailable{}
}

/*
CheckOrderStatusServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type CheckOrderStatusServiceUnavailable struct {
	Payload *models.ServiceTemporarilyUnavailable
}

// IsSuccess returns true when this check order status service unavailable response has a 2xx status code
func (o *CheckOrderStatusServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check order status service unavailable response has a 3xx status code
func (o *CheckOrderStatusServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check order status service unavailable response has a 4xx status code
func (o *CheckOrderStatusServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this check order status service unavailable response has a 5xx status code
func (o *CheckOrderStatusServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this check order status service unavailable response a status code equal to that given
func (o *CheckOrderStatusServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the check order status service unavailable response
func (o *CheckOrderStatusServiceUnavailable) Code() int {
	return 503
}

func (o *CheckOrderStatusServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusServiceUnavailable %s", 503, payload)
}

func (o *CheckOrderStatusServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/status/{order_id}][%d] checkOrderStatusServiceUnavailable %s", 503, payload)
}

func (o *CheckOrderStatusServiceUnavailable) GetPayload() *models.ServiceTemporarilyUnavailable {
	return o.Payload
}

func (o *CheckOrderStatusServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceTemporarilyUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
