// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-client/models"
)

// CreateBrigadeReader is a Reader for the CreateBrigade structure.
type CreateBrigadeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBrigadeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewCreateBrigadeAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateBrigadeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateBrigadeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateBrigadeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewCreateBrigadeServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /brigade] createBrigade", response, response.Code())
	}
}

// NewCreateBrigadeAccepted creates a CreateBrigadeAccepted with default headers values
func NewCreateBrigadeAccepted() *CreateBrigadeAccepted {
	return &CreateBrigadeAccepted{}
}

/*
CreateBrigadeAccepted describes a response with status code 202, with default header values.

Accepted
*/
type CreateBrigadeAccepted struct {

	/* Location

	   Format: uri
	*/
	Location strfmt.URI

	/* Retry after seconds

	   Format: int32
	*/
	RetryAfter string

	Payload *models.OrderStatus
}

// IsSuccess returns true when this create brigade accepted response has a 2xx status code
func (o *CreateBrigadeAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create brigade accepted response has a 3xx status code
func (o *CreateBrigadeAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create brigade accepted response has a 4xx status code
func (o *CreateBrigadeAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this create brigade accepted response has a 5xx status code
func (o *CreateBrigadeAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this create brigade accepted response a status code equal to that given
func (o *CreateBrigadeAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the create brigade accepted response
func (o *CreateBrigadeAccepted) Code() int {
	return 202
}

func (o *CreateBrigadeAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeAccepted %s", 202, payload)
}

func (o *CreateBrigadeAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeAccepted %s", 202, payload)
}

func (o *CreateBrigadeAccepted) GetPayload() *models.OrderStatus {
	return o.Payload
}

func (o *CreateBrigadeAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		vallocation, err := formats.Parse("uri", hdrLocation)
		if err != nil {
			return errors.InvalidType("Location", "header", "strfmt.URI", hdrLocation)
		}
		o.Location = *(vallocation.(*strfmt.URI))
	}

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		o.RetryAfter = hdrRetryAfter
	}

	o.Payload = new(models.OrderStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBrigadeBadRequest creates a CreateBrigadeBadRequest with default headers values
func NewCreateBrigadeBadRequest() *CreateBrigadeBadRequest {
	return &CreateBrigadeBadRequest{}
}

/*
CreateBrigadeBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateBrigadeBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create brigade bad request response has a 2xx status code
func (o *CreateBrigadeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create brigade bad request response has a 3xx status code
func (o *CreateBrigadeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create brigade bad request response has a 4xx status code
func (o *CreateBrigadeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create brigade bad request response has a 5xx status code
func (o *CreateBrigadeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create brigade bad request response a status code equal to that given
func (o *CreateBrigadeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create brigade bad request response
func (o *CreateBrigadeBadRequest) Code() int {
	return 400
}

func (o *CreateBrigadeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeBadRequest %s", 400, payload)
}

func (o *CreateBrigadeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeBadRequest %s", 400, payload)
}

func (o *CreateBrigadeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateBrigadeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBrigadeUnauthorized creates a CreateBrigadeUnauthorized with default headers values
func NewCreateBrigadeUnauthorized() *CreateBrigadeUnauthorized {
	return &CreateBrigadeUnauthorized{}
}

/*
CreateBrigadeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateBrigadeUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this create brigade unauthorized response has a 2xx status code
func (o *CreateBrigadeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create brigade unauthorized response has a 3xx status code
func (o *CreateBrigadeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create brigade unauthorized response has a 4xx status code
func (o *CreateBrigadeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create brigade unauthorized response has a 5xx status code
func (o *CreateBrigadeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create brigade unauthorized response a status code equal to that given
func (o *CreateBrigadeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create brigade unauthorized response
func (o *CreateBrigadeUnauthorized) Code() int {
	return 401
}

func (o *CreateBrigadeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeUnauthorized %s", 401, payload)
}

func (o *CreateBrigadeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeUnauthorized %s", 401, payload)
}

func (o *CreateBrigadeUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateBrigadeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBrigadeInternalServerError creates a CreateBrigadeInternalServerError with default headers values
func NewCreateBrigadeInternalServerError() *CreateBrigadeInternalServerError {
	return &CreateBrigadeInternalServerError{}
}

/*
CreateBrigadeInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateBrigadeInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create brigade internal server error response has a 2xx status code
func (o *CreateBrigadeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create brigade internal server error response has a 3xx status code
func (o *CreateBrigadeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create brigade internal server error response has a 4xx status code
func (o *CreateBrigadeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create brigade internal server error response has a 5xx status code
func (o *CreateBrigadeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create brigade internal server error response a status code equal to that given
func (o *CreateBrigadeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create brigade internal server error response
func (o *CreateBrigadeInternalServerError) Code() int {
	return 500
}

func (o *CreateBrigadeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeInternalServerError %s", 500, payload)
}

func (o *CreateBrigadeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeInternalServerError %s", 500, payload)
}

func (o *CreateBrigadeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateBrigadeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBrigadeServiceUnavailable creates a CreateBrigadeServiceUnavailable with default headers values
func NewCreateBrigadeServiceUnavailable() *CreateBrigadeServiceUnavailable {
	return &CreateBrigadeServiceUnavailable{}
}

/*
CreateBrigadeServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type CreateBrigadeServiceUnavailable struct {
	Payload *models.ServiceTemporarilyUnavailable
}

// IsSuccess returns true when this create brigade service unavailable response has a 2xx status code
func (o *CreateBrigadeServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create brigade service unavailable response has a 3xx status code
func (o *CreateBrigadeServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create brigade service unavailable response has a 4xx status code
func (o *CreateBrigadeServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this create brigade service unavailable response has a 5xx status code
func (o *CreateBrigadeServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this create brigade service unavailable response a status code equal to that given
func (o *CreateBrigadeServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the create brigade service unavailable response
func (o *CreateBrigadeServiceUnavailable) Code() int {
	return 503
}

func (o *CreateBrigadeServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeServiceUnavailable %s", 503, payload)
}

func (o *CreateBrigadeServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /brigade][%d] createBrigadeServiceUnavailable %s", 503, payload)
}

func (o *CreateBrigadeServiceUnavailable) GetPayload() *models.ServiceTemporarilyUnavailable {
	return o.Payload
}

func (o *CreateBrigadeServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceTemporarilyUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
