// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-client/models"
)

// DeleteBrigadeReader is a Reader for the DeleteBrigade structure.
type DeleteBrigadeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBrigadeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteBrigadeAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBrigadeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteBrigadeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteBrigadeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteBrigadeServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /brigade/{brigade_id}] deleteBrigade", response, response.Code())
	}
}

// NewDeleteBrigadeAccepted creates a DeleteBrigadeAccepted with default headers values
func NewDeleteBrigadeAccepted() *DeleteBrigadeAccepted {
	return &DeleteBrigadeAccepted{}
}

/*
DeleteBrigadeAccepted describes a response with status code 202, with default header values.

Accepted
*/
type DeleteBrigadeAccepted struct {

	/* Location

	   Format: uri
	*/
	Location strfmt.URI

	/* Retry after seconds

	   Format: int32
	*/
	RetryAfter string

	Payload *models.OrderStatus
}

// IsSuccess returns true when this delete brigade accepted response has a 2xx status code
func (o *DeleteBrigadeAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete brigade accepted response has a 3xx status code
func (o *DeleteBrigadeAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete brigade accepted response has a 4xx status code
func (o *DeleteBrigadeAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete brigade accepted response has a 5xx status code
func (o *DeleteBrigadeAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete brigade accepted response a status code equal to that given
func (o *DeleteBrigadeAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete brigade accepted response
func (o *DeleteBrigadeAccepted) Code() int {
	return 202
}

func (o *DeleteBrigadeAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeAccepted %s", 202, payload)
}

func (o *DeleteBrigadeAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeAccepted %s", 202, payload)
}

func (o *DeleteBrigadeAccepted) GetPayload() *models.OrderStatus {
	return o.Payload
}

func (o *DeleteBrigadeAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		vallocation, err := formats.Parse("uri", hdrLocation)
		if err != nil {
			return errors.InvalidType("Location", "header", "strfmt.URI", hdrLocation)
		}
		o.Location = *(vallocation.(*strfmt.URI))
	}

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		o.RetryAfter = hdrRetryAfter
	}

	o.Payload = new(models.OrderStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBrigadeBadRequest creates a DeleteBrigadeBadRequest with default headers values
func NewDeleteBrigadeBadRequest() *DeleteBrigadeBadRequest {
	return &DeleteBrigadeBadRequest{}
}

/*
DeleteBrigadeBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteBrigadeBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete brigade bad request response has a 2xx status code
func (o *DeleteBrigadeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete brigade bad request response has a 3xx status code
func (o *DeleteBrigadeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete brigade bad request response has a 4xx status code
func (o *DeleteBrigadeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete brigade bad request response has a 5xx status code
func (o *DeleteBrigadeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete brigade bad request response a status code equal to that given
func (o *DeleteBrigadeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete brigade bad request response
func (o *DeleteBrigadeBadRequest) Code() int {
	return 400
}

func (o *DeleteBrigadeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeBadRequest %s", 400, payload)
}

func (o *DeleteBrigadeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeBadRequest %s", 400, payload)
}

func (o *DeleteBrigadeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteBrigadeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBrigadeUnauthorized creates a DeleteBrigadeUnauthorized with default headers values
func NewDeleteBrigadeUnauthorized() *DeleteBrigadeUnauthorized {
	return &DeleteBrigadeUnauthorized{}
}

/*
DeleteBrigadeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteBrigadeUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete brigade unauthorized response has a 2xx status code
func (o *DeleteBrigadeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete brigade unauthorized response has a 3xx status code
func (o *DeleteBrigadeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete brigade unauthorized response has a 4xx status code
func (o *DeleteBrigadeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete brigade unauthorized response has a 5xx status code
func (o *DeleteBrigadeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete brigade unauthorized response a status code equal to that given
func (o *DeleteBrigadeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete brigade unauthorized response
func (o *DeleteBrigadeUnauthorized) Code() int {
	return 401
}

func (o *DeleteBrigadeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeUnauthorized %s", 401, payload)
}

func (o *DeleteBrigadeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeUnauthorized %s", 401, payload)
}

func (o *DeleteBrigadeUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteBrigadeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBrigadeInternalServerError creates a DeleteBrigadeInternalServerError with default headers values
func NewDeleteBrigadeInternalServerError() *DeleteBrigadeInternalServerError {
	return &DeleteBrigadeInternalServerError{}
}

/*
DeleteBrigadeInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteBrigadeInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete brigade internal server error response has a 2xx status code
func (o *DeleteBrigadeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete brigade internal server error response has a 3xx status code
func (o *DeleteBrigadeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete brigade internal server error response has a 4xx status code
func (o *DeleteBrigadeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete brigade internal server error response has a 5xx status code
func (o *DeleteBrigadeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete brigade internal server error response a status code equal to that given
func (o *DeleteBrigadeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete brigade internal server error response
func (o *DeleteBrigadeInternalServerError) Code() int {
	return 500
}

func (o *DeleteBrigadeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeInternalServerError %s", 500, payload)
}

func (o *DeleteBrigadeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeInternalServerError %s", 500, payload)
}

func (o *DeleteBrigadeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteBrigadeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBrigadeServiceUnavailable creates a DeleteBrigadeServiceUnavailable with default headers values
func NewDeleteBrigadeServiceUnavailable() *DeleteBrigadeServiceUnavailable {
	return &DeleteBrigadeServiceUnavailable{}
}

/*
DeleteBrigadeServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type DeleteBrigadeServiceUnavailable struct {
}

// IsSuccess returns true when this delete brigade service unavailable response has a 2xx status code
func (o *DeleteBrigadeServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete brigade service unavailable response has a 3xx status code
func (o *DeleteBrigadeServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete brigade service unavailable response has a 4xx status code
func (o *DeleteBrigadeServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete brigade service unavailable response has a 5xx status code
func (o *DeleteBrigadeServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete brigade service unavailable response a status code equal to that given
func (o *DeleteBrigadeServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete brigade service unavailable response
func (o *DeleteBrigadeServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteBrigadeServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeServiceUnavailable", 503)
}

func (o *DeleteBrigadeServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /brigade/{brigade_id}][%d] deleteBrigadeServiceUnavailable", 503)
}

func (o *DeleteBrigadeServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
