// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// BlockConfigOKCode is the HTTP code returned for type BlockConfigOK
const BlockConfigOKCode int = 200

/*
BlockConfigOK OK

swagger:response blockConfigOK
*/
type BlockConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.FreeSlots `json:"body,omitempty"`
}

// NewBlockConfigOK creates BlockConfigOK with default headers values
func NewBlockConfigOK() *BlockConfigOK {

	return &BlockConfigOK{}
}

// WithPayload adds the payload to the block config o k response
func (o *BlockConfigOK) WithPayload(payload *models.FreeSlots) *BlockConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config o k response
func (o *BlockConfigOK) SetPayload(payload *models.FreeSlots) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BlockConfigBadRequestCode is the HTTP code returned for type BlockConfigBadRequest
const BlockConfigBadRequestCode int = 400

/*
BlockConfigBadRequest Bad Request

swagger:response blockConfigBadRequest
*/
type BlockConfigBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBlockConfigBadRequest creates BlockConfigBadRequest with default headers values
func NewBlockConfigBadRequest() *BlockConfigBadRequest {

	return &BlockConfigBadRequest{}
}

// WithPayload adds the payload to the block config bad request response
func (o *BlockConfigBadRequest) WithPayload(payload *models.Error) *BlockConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config bad request response
func (o *BlockConfigBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BlockConfigUnauthorizedCode is the HTTP code returned for type BlockConfigUnauthorized
const BlockConfigUnauthorizedCode int = 401

/*
BlockConfigUnauthorized Unauthorized

swagger:response blockConfigUnauthorized
*/
type BlockConfigUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBlockConfigUnauthorized creates BlockConfigUnauthorized with default headers values
func NewBlockConfigUnauthorized() *BlockConfigUnauthorized {

	return &BlockConfigUnauthorized{}
}

// WithPayload adds the payload to the block config unauthorized response
func (o *BlockConfigUnauthorized) WithPayload(payload *models.Error) *BlockConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config unauthorized response
func (o *BlockConfigUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BlockConfigNotFoundCode is the HTTP code returned for type BlockConfigNotFound
const BlockConfigNotFoundCode int = 404

/*
BlockConfigNotFound Not Found

swagger:response blockConfigNotFound
*/
type BlockConfigNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBlockConfigNotFound creates BlockConfigNotFound with default headers values
func NewBlockConfigNotFound() *BlockConfigNotFound {

	return &BlockConfigNotFound{}
}

// WithPayload adds the payload to the block config not found response
func (o *BlockConfigNotFound) WithPayload(payload *models.Error) *BlockConfigNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config not found response
func (o *BlockConfigNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BlockConfigInternalServerErrorCode is the HTTP code returned for type BlockConfigInternalServerError
const BlockConfigInternalServerErrorCode int = 500

/*
BlockConfigInternalServerError Internal Server Error

swagger:response blockConfigInternalServerError
*/
type BlockConfigInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBlockConfigInternalServerError creates BlockConfigInternalServerError with default headers values
func NewBlockConfigInternalServerError() *BlockConfigInternalServerError {

	return &BlockConfigInternalServerError{}
}

// WithPayload adds the payload to the block config internal server error response
func (o *BlockConfigInternalServerError) WithPayload(payload *models.Error) *BlockConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config internal server error response
func (o *BlockConfigInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BlockConfigServiceUnavailableCode is the HTTP code returned for type BlockConfigServiceUnavailable
const BlockConfigServiceUnavailableCode int = 503

/*
BlockConfigServiceUnavailable Service Temporarily Unavailable

swagger:response blockConfigServiceUnavailable
*/
type BlockConfigServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceTemporarilyUnavailable `json:"body,omitempty"`
}

// NewBlockConfigServiceUnavailable creates BlockConfigServiceUnavailable with default headers values
func NewBlockConfigServiceUnavailable() *BlockConfigServiceUnavailable {

	return &BlockConfigServiceUnavailable{}
}

// WithPayload adds the payload to the block config service unavailable response
func (o *BlockConfigServiceUnavailable) WithPayload(payload *models.ServiceTemporarilyUnavailable) *BlockConfigServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the block config service unavailable response
func (o *BlockConfigServiceUnavailable) SetPayload(payload *models.ServiceTemporarilyUnavailable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BlockConfigServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
