// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// CreateBrigadeHandlerFunc turns a function with the right signature into a create brigade handler
type CreateBrigadeHandlerFunc func(CreateBrigadeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateBrigadeHandlerFunc) Handle(params CreateBrigadeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateBrigadeHandler interface for that can handle valid create brigade params
type CreateBrigadeHandler interface {
	Handle(CreateBrigadeParams, *models.Principal) middleware.Responder
}

// NewCreateBrigade creates a new http.Handler for the create brigade operation
func NewCreateBrigade(ctx *middleware.Context, handler CreateBrigadeHandler) *CreateBrigade {
	return &CreateBrigade{Context: ctx, Handler: handler}
}

/*
	CreateBrigade swagger:route POST /brigade createBrigade

Create VPN brigade
*/
type CreateBrigade struct {
	Context *middleware.Context
	Handler CreateBrigadeHandler
}

func (o *CreateBrigade) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateBrigadeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
