// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// CreateConfigHandlerFunc turns a function with the right signature into a create config handler
type CreateConfigHandlerFunc func(CreateConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateConfigHandlerFunc) Handle(params CreateConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateConfigHandler interface for that can handle valid create config params
type CreateConfigHandler interface {
	Handle(CreateConfigParams, *models.Principal) middleware.Responder
}

// NewCreateConfig creates a new http.Handler for the create config operation
func NewCreateConfig(ctx *middleware.Context, handler CreateConfigHandler) *CreateConfig {
	return &CreateConfig{Context: ctx, Handler: handler}
}

/*
	CreateConfig swagger:route POST /config createConfig

Create VPN config
*/
type CreateConfig struct {
	Context *middleware.Context
	Handler CreateConfigHandler
}

func (o *CreateConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
