// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// DeleteBrigadeHandlerFunc turns a function with the right signature into a delete brigade handler
type DeleteBrigadeHandlerFunc func(DeleteBrigadeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBrigadeHandlerFunc) Handle(params DeleteBrigadeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteBrigadeHandler interface for that can handle valid delete brigade params
type DeleteBrigadeHandler interface {
	Handle(DeleteBrigadeParams, *models.Principal) middleware.Responder
}

// NewDeleteBrigade creates a new http.Handler for the delete brigade operation
func NewDeleteBrigade(ctx *middleware.Context, handler DeleteBrigadeHandler) *DeleteBrigade {
	return &DeleteBrigade{Context: ctx, Handler: handler}
}

/*
	DeleteBrigade swagger:route DELETE /brigade/{brigade_id} deleteBrigade

Delete VPN brigade
*/
type DeleteBrigade struct {
	Context *middleware.Context
	Handler DeleteBrigadeHandler
}

func (o *DeleteBrigade) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBrigadeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
