// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// DeleteConfigNoContentCode is the HTTP code returned for type DeleteConfigNoContent
const DeleteConfigNoContentCode int = 204

/*
DeleteConfigNoContent No Content

swagger:response deleteConfigNoContent
*/
type DeleteConfigNoContent struct {
}

// NewDeleteConfigNoContent creates DeleteConfigNoContent with default headers values
func NewDeleteConfigNoContent() *DeleteConfigNoContent {

	return &DeleteConfigNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConfigBadRequestCode is the HTTP code returned for type DeleteConfigBadRequest
const DeleteConfigBadRequestCode int = 400

/*
DeleteConfigBadRequest Bad Request

swagger:response deleteConfigBadRequest
*/
type DeleteConfigBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigBadRequest creates DeleteConfigBadRequest with default headers values
func NewDeleteConfigBadRequest() *DeleteConfigBadRequest {

	return &DeleteConfigBadRequest{}
}

// WithPayload adds the payload to the delete config bad request response
func (o *DeleteConfigBadRequest) WithPayload(payload *models.Error) *DeleteConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config bad request response
func (o *DeleteConfigBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigUnauthorizedCode is the HTTP code returned for type DeleteConfigUnauthorized
const DeleteConfigUnauthorizedCode int = 401

/*
DeleteConfigUnauthorized Unauthorized

swagger:response deleteConfigUnauthorized
*/
type DeleteConfigUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigUnauthorized creates DeleteConfigUnauthorized with default headers values
func NewDeleteConfigUnauthorized() *DeleteConfigUnauthorized {

	return &DeleteConfigUnauthorized{}
}

// WithPayload adds the payload to the delete config unauthorized response
func (o *DeleteConfigUnauthorized) WithPayload(payload *models.Error) *DeleteConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config unauthorized response
func (o *DeleteConfigUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigInternalServerErrorCode is the HTTP code returned for type DeleteConfigInternalServerError
const DeleteConfigInternalServerErrorCode int = 500

/*
DeleteConfigInternalServerError Internal Server Error

swagger:response deleteConfigInternalServerError
*/
type DeleteConfigInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigInternalServerError creates DeleteConfigInternalServerError with default headers values
func NewDeleteConfigInternalServerError() *DeleteConfigInternalServerError {

	return &DeleteConfigInternalServerError{}
}

// WithPayload adds the payload to the delete config internal server error response
func (o *DeleteConfigInternalServerError) WithPayload(payload *models.Error) *DeleteConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config internal server error response
func (o *DeleteConfigInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigServiceUnavailableCode is the HTTP code returned for type DeleteConfigServiceUnavailable
const DeleteConfigServiceUnavailableCode int = 503

/*
DeleteConfigServiceUnavailable Service Temporarily Unavailable

swagger:response deleteConfigServiceUnavailable
*/
type DeleteConfigServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceTemporarilyUnavailable `json:"body,omitempty"`
}

// NewDeleteConfigServiceUnavailable creates DeleteConfigServiceUnavailable with default headers values
func NewDeleteConfigServiceUnavailable() *DeleteConfigServiceUnavailable {

	return &DeleteConfigServiceUnavailable{}
}

// WithPayload adds the payload to the delete config service unavailable response
func (o *DeleteConfigServiceUnavailable) WithPayload(payload *models.ServiceTemporarilyUnavailable) *DeleteConfigServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config service unavailable response
func (o *DeleteConfigServiceUnavailable) SetPayload(payload *models.ServiceTemporarilyUnavailable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
