// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// DeleteConfigHandlerFunc turns a function with the right signature into a delete config handler
type DeleteConfigHandlerFunc func(DeleteConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigHandlerFunc) Handle(params DeleteConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigHandler interface for that can handle valid delete config params
type DeleteConfigHandler interface {
	Handle(DeleteConfigParams, *models.Principal) middleware.Responder
}

// NewDeleteConfig creates a new http.Handler for the delete config operation
func NewDeleteConfig(ctx *middleware.Context, handler DeleteConfigHandler) *DeleteConfig {
	return &DeleteConfig{Context: ctx, Handler: handler}
}

/*
	DeleteConfig swagger:route DELETE /config/{config_id} deleteConfig

Delete VPN config
*/
type DeleteConfig struct {
	Context *middleware.Context
	Handler DeleteConfigHandler
}

func (o *DeleteConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteConfigBody delete config body
//
// swagger:model DeleteConfigBody
type DeleteConfigBody struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigadeID"`
}

// Validate validates this delete config body
func (o *DeleteConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteConfigBody) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"brigadeID", "body", o.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"brigadeID", "body", "uuid", o.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete config body based on context it is used
func (o *DeleteConfigBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteConfigBody) UnmarshalBinary(b []byte) error {
	var res DeleteConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
