// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetBrigadeActivityParams creates a new GetBrigadeActivityParams object
//
// There are no default values defined in the spec.
func NewGetBrigadeActivityParams() GetBrigadeActivityParams {

	return GetBrigadeActivityParams{}
}

// GetBrigadeActivityParams contains all the bound params for the get brigade activity operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBrigadeActivity
type GetBrigadeActivityParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Brigade ID
	  Required: true
	  In: path
	*/
	BrigadeID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBrigadeActivityParams() beforehand.
func (o *GetBrigadeActivityParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBrigadeID, rhkBrigadeID, _ := route.Params.GetOK("brigade_id")
	if err := o.bindBrigadeID(rBrigadeID, rhkBrigadeID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBrigadeID binds and validates parameter BrigadeID from path.
func (o *GetBrigadeActivityParams) bindBrigadeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BrigadeID = raw

	return nil
}
