// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// GetBrigadeSlotsOKCode is the HTTP code returned for type GetBrigadeSlotsOK
const GetBrigadeSlotsOKCode int = 200

/*
GetBrigadeSlotsOK OK

swagger:response getBrigadeSlotsOK
*/
type GetBrigadeSlotsOK struct {

	/*
	  In: Body
	*/
	Payload *models.BrigadeSlots `json:"body,omitempty"`
}

// NewGetBrigadeSlotsOK creates GetBrigadeSlotsOK with default headers values
func NewGetBrigadeSlotsOK() *GetBrigadeSlotsOK {

	return &GetBrigadeSlotsOK{}
}

// WithPayload adds the payload to the get brigade slots o k response
func (o *GetBrigadeSlotsOK) WithPayload(payload *models.BrigadeSlots) *GetBrigadeSlotsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade slots o k response
func (o *GetBrigadeSlotsOK) SetPayload(payload *models.BrigadeSlots) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeSlotsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeSlotsBadRequestCode is the HTTP code returned for type GetBrigadeSlotsBadRequest
const GetBrigadeSlotsBadRequestCode int = 400

/*
GetBrigadeSlotsBadRequest Bad Request

swagger:response getBrigadeSlotsBadRequest
*/
type GetBrigadeSlotsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeSlotsBadRequest creates GetBrigadeSlotsBadRequest with default headers values
func NewGetBrigadeSlotsBadRequest() *GetBrigadeSlotsBadRequest {

	return &GetBrigadeSlotsBadRequest{}
}

// WithPayload adds the payload to the get brigade slots bad request response
func (o *GetBrigadeSlotsBadRequest) WithPayload(payload *models.Error) *GetBrigadeSlotsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade slots bad request response
func (o *GetBrigadeSlotsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeSlotsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeSlotsUnauthorizedCode is the HTTP code returned for type GetBrigadeSlotsUnauthorized
const GetBrigadeSlotsUnauthorizedCode int = 401

/*
GetBrigadeSlotsUnauthorized Unauthorized

swagger:response getBrigadeSlotsUnauthorized
*/
type GetBrigadeSlotsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeSlotsUnauthorized creates GetBrigadeSlotsUnauthorized with default headers values
func NewGetBrigadeSlotsUnauthorized() *GetBrigadeSlotsUnauthorized {

	return &GetBrigadeSlotsUnauthorized{}
}

// WithPayload adds the payload to the get brigade slots unauthorized response
func (o *GetBrigadeSlotsUnauthorized) WithPayload(payload *models.Error) *GetBrigadeSlotsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade slots unauthorized response
func (o *GetBrigadeSlotsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeSlotsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeSlotsInternalServerErrorCode is the HTTP code returned for type GetBrigadeSlotsInternalServerError
const GetBrigadeSlotsInternalServerErrorCode int = 500

/*
GetBrigadeSlotsInternalServerError Internal Server Error

swagger:response getBrigadeSlotsInternalServerError
*/
type GetBrigadeSlotsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeSlotsInternalServerError creates GetBrigadeSlotsInternalServerError with default headers values
func NewGetBrigadeSlotsInternalServerError() *GetBrigadeSlotsInternalServerError {

	return &GetBrigadeSlotsInternalServerError{}
}

// WithPayload adds the payload to the get brigade slots internal server error response
func (o *GetBrigadeSlotsInternalServerError) WithPayload(payload *models.Error) *GetBrigadeSlotsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade slots internal server error response
func (o *GetBrigadeSlotsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeSlotsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeSlotsServiceUnavailableCode is the HTTP code returned for type GetBrigadeSlotsServiceUnavailable
const GetBrigadeSlotsServiceUnavailableCode int = 503

/*
GetBrigadeSlotsServiceUnavailable Service Temporarily Unavailable

swagger:response getBrigadeSlotsServiceUnavailable
*/
type GetBrigadeSlotsServiceUnavailable struct {
}

// NewGetBrigadeSlotsServiceUnavailable creates GetBrigadeSlotsServiceUnavailable with default headers values
func NewGetBrigadeSlotsServiceUnavailable() *GetBrigadeSlotsServiceUnavailable {

	return &GetBrigadeSlotsServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetBrigadeSlotsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
