// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// UnblockConfigHandlerFunc turns a function with the right signature into a unblock config handler
type UnblockConfigHandlerFunc func(UnblockConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UnblockConfigHandlerFunc) Handle(params UnblockConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UnblockConfigHandler interface for that can handle valid unblock config params
type UnblockConfigHandler interface {
	Handle(UnblockConfigParams, *models.Principal) middleware.Responder
}

// NewUnblockConfig creates a new http.Handler for the unblock config operation
func NewUnblockConfig(ctx *middleware.Context, handler UnblockConfigHandler) *UnblockConfig {
	return &UnblockConfig{Context: ctx, Handler: handler}
}

/*
	UnblockConfig swagger:route PATCH /config/{config_id}/unblock unblockConfig

Unblock VPN config
*/
type UnblockConfig struct {
	Context *middleware.Context
	Handler UnblockConfigHandler
}

func (o *UnblockConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUnblockConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UnblockConfigBody unblock config body
//
// swagger:model UnblockConfigBody
type UnblockConfigBody struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`
}

// Validate validates this unblock config body
func (o *UnblockConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UnblockConfigBody) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"brigade_id", "body", o.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"brigade_id", "body", "uuid", o.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this unblock config body based on context it is used
func (o *UnblockConfigBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UnblockConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UnblockConfigBody) UnmarshalBinary(b []byte) error {
	var res UnblockConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
