// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-server/models"
)

// UnblockConfigOKCode is the HTTP code returned for type UnblockConfigOK
const UnblockConfigOKCode int = 200

/*
UnblockConfigOK OK

swagger:response unblockConfigOK
*/
type UnblockConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.FreeSlots `json:"body,omitempty"`
}

// NewUnblockConfigOK creates UnblockConfigOK with default headers values
func NewUnblockConfigOK() *UnblockConfigOK {

	return &UnblockConfigOK{}
}

// WithPayload adds the payload to the unblock config o k response
func (o *UnblockConfigOK) WithPayload(payload *models.FreeSlots) *UnblockConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config o k response
func (o *UnblockConfigOK) SetPayload(payload *models.FreeSlots) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UnblockConfigBadRequestCode is the HTTP code returned for type UnblockConfigBadRequest
const UnblockConfigBadRequestCode int = 400

/*
UnblockConfigBadRequest Bad Request

swagger:response unblockConfigBadRequest
*/
type UnblockConfigBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnblockConfigBadRequest creates UnblockConfigBadRequest with default headers values
func NewUnblockConfigBadRequest() *UnblockConfigBadRequest {

	return &UnblockConfigBadRequest{}
}

// WithPayload adds the payload to the unblock config bad request response
func (o *UnblockConfigBadRequest) WithPayload(payload *models.Error) *UnblockConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config bad request response
func (o *UnblockConfigBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UnblockConfigUnauthorizedCode is the HTTP code returned for type UnblockConfigUnauthorized
const UnblockConfigUnauthorizedCode int = 401

/*
UnblockConfigUnauthorized Unauthorized

swagger:response unblockConfigUnauthorized
*/
type UnblockConfigUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnblockConfigUnauthorized creates UnblockConfigUnauthorized with default headers values
func NewUnblockConfigUnauthorized() *UnblockConfigUnauthorized {

	return &UnblockConfigUnauthorized{}
}

// WithPayload adds the payload to the unblock config unauthorized response
func (o *UnblockConfigUnauthorized) WithPayload(payload *models.Error) *UnblockConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config unauthorized response
func (o *UnblockConfigUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UnblockConfigNotFoundCode is the HTTP code returned for type UnblockConfigNotFound
const UnblockConfigNotFoundCode int = 404

/*
UnblockConfigNotFound Not Found

swagger:response unblockConfigNotFound
*/
type UnblockConfigNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnblockConfigNotFound creates UnblockConfigNotFound with default headers values
func NewUnblockConfigNotFound() *UnblockConfigNotFound {

	return &UnblockConfigNotFound{}
}

// WithPayload adds the payload to the unblock config not found response
func (o *UnblockConfigNotFound) WithPayload(payload *models.Error) *UnblockConfigNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config not found response
func (o *UnblockConfigNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UnblockConfigInternalServerErrorCode is the HTTP code returned for type UnblockConfigInternalServerError
const UnblockConfigInternalServerErrorCode int = 500

/*
UnblockConfigInternalServerError Internal Server Error

swagger:response unblockConfigInternalServerError
*/
type UnblockConfigInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnblockConfigInternalServerError creates UnblockConfigInternalServerError with default headers values
func NewUnblockConfigInternalServerError() *UnblockConfigInternalServerError {

	return &UnblockConfigInternalServerError{}
}

// WithPayload adds the payload to the unblock config internal server error response
func (o *UnblockConfigInternalServerError) WithPayload(payload *models.Error) *UnblockConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config internal server error response
func (o *UnblockConfigInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UnblockConfigServiceUnavailableCode is the HTTP code returned for type UnblockConfigServiceUnavailable
const UnblockConfigServiceUnavailableCode int = 503

/*
UnblockConfigServiceUnavailable Service Temporarily Unavailable

swagger:response unblockConfigServiceUnavailable
*/
type UnblockConfigServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceTemporarilyUnavailable `json:"body,omitempty"`
}

// NewUnblockConfigServiceUnavailable creates UnblockConfigServiceUnavailable with default headers values
func NewUnblockConfigServiceUnavailable() *UnblockConfigServiceUnavailable {

	return &UnblockConfigServiceUnavailable{}
}

// WithPayload adds the payload to the unblock config service unavailable response
func (o *UnblockConfigServiceUnavailable) WithPayload(payload *models.ServiceTemporarilyUnavailable) *UnblockConfigServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unblock config service unavailable response
func (o *UnblockConfigServiceUnavailable) SetPayload(payload *models.ServiceTemporarilyUnavailable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnblockConfigServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
