#!/bin/sh

if [ "x$1" = "xpkg" ]; then
        set -e

        export USER_UID=${USER_UID}

        ssh-keyscan -t rsa github.com >> /etc/ssh/ssh_known_hosts
        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
        go env -w GOPRIVATE=github.com/vpngen

        git clone ssh://git@github.com/vpngen/realm-admin

        realm-admin/tarpkg/build-pkg.sh

        exit 0
fi


AUTH_KEY="ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMtZz9Q09I41faeyLIWEijSCFSp8bAbvX2dHUhKxGmJ7nPmqGhXDtDCDF3D1RiNMMQGMzrIaDZWq8WIy98eq2zI= root@vg-wolfs-mgmt"

docker run --rm -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -e AUTH_KEY="${AUTH_KEY}" -e USER_UID=`id -u` -v ${PWD}:/data golang:1.19 /data/build pkg

