// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FreeSlots free slots
//
// swagger:model FreeSlots
type FreeSlots struct {

	// free slots
	// Required: true
	FreeSlots *int64 `json:"free_slots"`
}

// Validate validates this free slots
func (m *FreeSlots) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFreeSlots(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FreeSlots) validateFreeSlots(formats strfmt.Registry) error {

	if err := validate.Required("free_slots", "body", m.FreeSlots); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this free slots based on context it is used
func (m *FreeSlots) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FreeSlots) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FreeSlots) UnmarshalBinary(b []byte) error {
	var res FreeSlots
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
