// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderStatus order status
//
// swagger:model OrderStatus
type OrderStatus struct {

	// Message
	// Required: true
	Message *string `json:"message"`

	// Order ID
	// Format: uuid
	OrderID strfmt.UUID `json:"order_id,omitempty"`

	// Retry after seconds
	RetryAfter int64 `json:"retryAfter,omitempty"`

	// Order status
	// Required: true
	// Enum: ["created","processing","completed","failed"]
	Status *string `json:"status"`
}

// Validate validates this order status
func (m *OrderStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderStatus) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *OrderStatus) validateOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("order_id", "body", "uuid", m.OrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

var orderStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["created","processing","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderStatusTypeStatusPropEnum = append(orderStatusTypeStatusPropEnum, v)
	}
}

const (

	// OrderStatusStatusCreated captures enum value "created"
	OrderStatusStatusCreated string = "created"

	// OrderStatusStatusProcessing captures enum value "processing"
	OrderStatusStatusProcessing string = "processing"

	// OrderStatusStatusCompleted captures enum value "completed"
	OrderStatusStatusCompleted string = "completed"

	// OrderStatusStatusFailed captures enum value "failed"
	OrderStatusStatusFailed string = "failed"
)

// prop value enum
func (m *OrderStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *OrderStatus) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order status based on context it is used
func (m *OrderStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderStatus) UnmarshalBinary(b []byte) error {
	var res OrderStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
