// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceTemporarilyUnavailable service temporarily unavailable
//
// swagger:model ServiceTemporarilyUnavailable
type ServiceTemporarilyUnavailable struct {

	// Error code
	Code int64 `json:"code,omitempty"`

	// Error message
	Message string `json:"message,omitempty"`
}

// Validate validates this service temporarily unavailable
func (m *ServiceTemporarilyUnavailable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service temporarily unavailable based on context it is used
func (m *ServiceTemporarilyUnavailable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceTemporarilyUnavailable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceTemporarilyUnavailable) UnmarshalBinary(b []byte) error {
	var res ServiceTemporarilyUnavailable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
