// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-server/models"
)

// CreateBrigadeAcceptedCode is the HTTP code returned for type CreateBrigadeAccepted
const CreateBrigadeAcceptedCode int = 202

/*
CreateBrigadeAccepted Accepted

swagger:response createBrigadeAccepted
*/
type CreateBrigadeAccepted struct {
	/*Location

	 */
	Location strfmt.URI `json:"Location"`
	/*Retry after seconds

	 */
	RetryAfter string `json:"Retry-After"`

	/*
	  In: Body
	*/
	Payload *models.OrderStatus `json:"body,omitempty"`
}

// NewCreateBrigadeAccepted creates CreateBrigadeAccepted with default headers values
func NewCreateBrigadeAccepted() *CreateBrigadeAccepted {

	return &CreateBrigadeAccepted{}
}

// WithLocation adds the location to the create brigade accepted response
func (o *CreateBrigadeAccepted) WithLocation(location strfmt.URI) *CreateBrigadeAccepted {
	o.Location = location
	return o
}

// SetLocation sets the location to the create brigade accepted response
func (o *CreateBrigadeAccepted) SetLocation(location strfmt.URI) {
	o.Location = location
}

// WithRetryAfter adds the retryAfter to the create brigade accepted response
func (o *CreateBrigadeAccepted) WithRetryAfter(retryAfter string) *CreateBrigadeAccepted {
	o.RetryAfter = retryAfter
	return o
}

// SetRetryAfter sets the retryAfter to the create brigade accepted response
func (o *CreateBrigadeAccepted) SetRetryAfter(retryAfter string) {
	o.RetryAfter = retryAfter
}

// WithPayload adds the payload to the create brigade accepted response
func (o *CreateBrigadeAccepted) WithPayload(payload *models.OrderStatus) *CreateBrigadeAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create brigade accepted response
func (o *CreateBrigadeAccepted) SetPayload(payload *models.OrderStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBrigadeAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location.String()
	if location != "" {
		rw.Header().Set("Location", location)
	}

	// response header Retry-After

	retryAfter := o.RetryAfter
	if retryAfter != "" {
		rw.Header().Set("Retry-After", retryAfter)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBrigadeBadRequestCode is the HTTP code returned for type CreateBrigadeBadRequest
const CreateBrigadeBadRequestCode int = 400

/*
CreateBrigadeBadRequest Bad Request

swagger:response createBrigadeBadRequest
*/
type CreateBrigadeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBrigadeBadRequest creates CreateBrigadeBadRequest with default headers values
func NewCreateBrigadeBadRequest() *CreateBrigadeBadRequest {

	return &CreateBrigadeBadRequest{}
}

// WithPayload adds the payload to the create brigade bad request response
func (o *CreateBrigadeBadRequest) WithPayload(payload *models.Error) *CreateBrigadeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create brigade bad request response
func (o *CreateBrigadeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBrigadeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBrigadeUnauthorizedCode is the HTTP code returned for type CreateBrigadeUnauthorized
const CreateBrigadeUnauthorizedCode int = 401

/*
CreateBrigadeUnauthorized Unauthorized

swagger:response createBrigadeUnauthorized
*/
type CreateBrigadeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBrigadeUnauthorized creates CreateBrigadeUnauthorized with default headers values
func NewCreateBrigadeUnauthorized() *CreateBrigadeUnauthorized {

	return &CreateBrigadeUnauthorized{}
}

// WithPayload adds the payload to the create brigade unauthorized response
func (o *CreateBrigadeUnauthorized) WithPayload(payload *models.Error) *CreateBrigadeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create brigade unauthorized response
func (o *CreateBrigadeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBrigadeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBrigadeInternalServerErrorCode is the HTTP code returned for type CreateBrigadeInternalServerError
const CreateBrigadeInternalServerErrorCode int = 500

/*
CreateBrigadeInternalServerError Internal Server Error

swagger:response createBrigadeInternalServerError
*/
type CreateBrigadeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBrigadeInternalServerError creates CreateBrigadeInternalServerError with default headers values
func NewCreateBrigadeInternalServerError() *CreateBrigadeInternalServerError {

	return &CreateBrigadeInternalServerError{}
}

// WithPayload adds the payload to the create brigade internal server error response
func (o *CreateBrigadeInternalServerError) WithPayload(payload *models.Error) *CreateBrigadeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create brigade internal server error response
func (o *CreateBrigadeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBrigadeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBrigadeServiceUnavailableCode is the HTTP code returned for type CreateBrigadeServiceUnavailable
const CreateBrigadeServiceUnavailableCode int = 503

/*
CreateBrigadeServiceUnavailable Service Temporarily Unavailable

swagger:response createBrigadeServiceUnavailable
*/
type CreateBrigadeServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceTemporarilyUnavailable `json:"body,omitempty"`
}

// NewCreateBrigadeServiceUnavailable creates CreateBrigadeServiceUnavailable with default headers values
func NewCreateBrigadeServiceUnavailable() *CreateBrigadeServiceUnavailable {

	return &CreateBrigadeServiceUnavailable{}
}

// WithPayload adds the payload to the create brigade service unavailable response
func (o *CreateBrigadeServiceUnavailable) WithPayload(payload *models.ServiceTemporarilyUnavailable) *CreateBrigadeServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create brigade service unavailable response
func (o *CreateBrigadeServiceUnavailable) SetPayload(payload *models.ServiceTemporarilyUnavailable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBrigadeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
