// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-server/models"
)

// DeleteBrigadeAcceptedCode is the HTTP code returned for type DeleteBrigadeAccepted
const DeleteBrigadeAcceptedCode int = 202

/*
DeleteBrigadeAccepted Accepted

swagger:response deleteBrigadeAccepted
*/
type DeleteBrigadeAccepted struct {
	/*Location

	 */
	Location strfmt.URI `json:"Location"`
	/*Retry after seconds

	 */
	RetryAfter string `json:"Retry-After"`

	/*
	  In: Body
	*/
	Payload *models.OrderStatus `json:"body,omitempty"`
}

// NewDeleteBrigadeAccepted creates DeleteBrigadeAccepted with default headers values
func NewDeleteBrigadeAccepted() *DeleteBrigadeAccepted {

	return &DeleteBrigadeAccepted{}
}

// WithLocation adds the location to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) WithLocation(location strfmt.URI) *DeleteBrigadeAccepted {
	o.Location = location
	return o
}

// SetLocation sets the location to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) SetLocation(location strfmt.URI) {
	o.Location = location
}

// WithRetryAfter adds the retryAfter to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) WithRetryAfter(retryAfter string) *DeleteBrigadeAccepted {
	o.RetryAfter = retryAfter
	return o
}

// SetRetryAfter sets the retryAfter to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) SetRetryAfter(retryAfter string) {
	o.RetryAfter = retryAfter
}

// WithPayload adds the payload to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) WithPayload(payload *models.OrderStatus) *DeleteBrigadeAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete brigade accepted response
func (o *DeleteBrigadeAccepted) SetPayload(payload *models.OrderStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBrigadeAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location.String()
	if location != "" {
		rw.Header().Set("Location", location)
	}

	// response header Retry-After

	retryAfter := o.RetryAfter
	if retryAfter != "" {
		rw.Header().Set("Retry-After", retryAfter)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBrigadeBadRequestCode is the HTTP code returned for type DeleteBrigadeBadRequest
const DeleteBrigadeBadRequestCode int = 400

/*
DeleteBrigadeBadRequest Bad Request

swagger:response deleteBrigadeBadRequest
*/
type DeleteBrigadeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBrigadeBadRequest creates DeleteBrigadeBadRequest with default headers values
func NewDeleteBrigadeBadRequest() *DeleteBrigadeBadRequest {

	return &DeleteBrigadeBadRequest{}
}

// WithPayload adds the payload to the delete brigade bad request response
func (o *DeleteBrigadeBadRequest) WithPayload(payload *models.Error) *DeleteBrigadeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete brigade bad request response
func (o *DeleteBrigadeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBrigadeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBrigadeUnauthorizedCode is the HTTP code returned for type DeleteBrigadeUnauthorized
const DeleteBrigadeUnauthorizedCode int = 401

/*
DeleteBrigadeUnauthorized Unauthorized

swagger:response deleteBrigadeUnauthorized
*/
type DeleteBrigadeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBrigadeUnauthorized creates DeleteBrigadeUnauthorized with default headers values
func NewDeleteBrigadeUnauthorized() *DeleteBrigadeUnauthorized {

	return &DeleteBrigadeUnauthorized{}
}

// WithPayload adds the payload to the delete brigade unauthorized response
func (o *DeleteBrigadeUnauthorized) WithPayload(payload *models.Error) *DeleteBrigadeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete brigade unauthorized response
func (o *DeleteBrigadeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBrigadeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBrigadeInternalServerErrorCode is the HTTP code returned for type DeleteBrigadeInternalServerError
const DeleteBrigadeInternalServerErrorCode int = 500

/*
DeleteBrigadeInternalServerError Internal Server Error

swagger:response deleteBrigadeInternalServerError
*/
type DeleteBrigadeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBrigadeInternalServerError creates DeleteBrigadeInternalServerError with default headers values
func NewDeleteBrigadeInternalServerError() *DeleteBrigadeInternalServerError {

	return &DeleteBrigadeInternalServerError{}
}

// WithPayload adds the payload to the delete brigade internal server error response
func (o *DeleteBrigadeInternalServerError) WithPayload(payload *models.Error) *DeleteBrigadeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete brigade internal server error response
func (o *DeleteBrigadeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBrigadeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBrigadeServiceUnavailableCode is the HTTP code returned for type DeleteBrigadeServiceUnavailable
const DeleteBrigadeServiceUnavailableCode int = 503

/*
DeleteBrigadeServiceUnavailable Service Temporarily Unavailable

swagger:response deleteBrigadeServiceUnavailable
*/
type DeleteBrigadeServiceUnavailable struct {
}

// NewDeleteBrigadeServiceUnavailable creates DeleteBrigadeServiceUnavailable with default headers values
func NewDeleteBrigadeServiceUnavailable() *DeleteBrigadeServiceUnavailable {

	return &DeleteBrigadeServiceUnavailable{}
}

// WriteResponse to the client
func (o *DeleteBrigadeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
