// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-server/models"
)

// GetBrigadeOKCode is the HTTP code returned for type GetBrigadeOK
const GetBrigadeOKCode int = 200

/*
GetBrigadeOK OK

swagger:response getBrigadeOK
*/
type GetBrigadeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Brigade `json:"body,omitempty"`
}

// NewGetBrigadeOK creates GetBrigadeOK with default headers values
func NewGetBrigadeOK() *GetBrigadeOK {

	return &GetBrigadeOK{}
}

// WithPayload adds the payload to the get brigade o k response
func (o *GetBrigadeOK) WithPayload(payload *models.Brigade) *GetBrigadeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade o k response
func (o *GetBrigadeOK) SetPayload(payload *models.Brigade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeBadRequestCode is the HTTP code returned for type GetBrigadeBadRequest
const GetBrigadeBadRequestCode int = 400

/*
GetBrigadeBadRequest Bad Request

swagger:response getBrigadeBadRequest
*/
type GetBrigadeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeBadRequest creates GetBrigadeBadRequest with default headers values
func NewGetBrigadeBadRequest() *GetBrigadeBadRequest {

	return &GetBrigadeBadRequest{}
}

// WithPayload adds the payload to the get brigade bad request response
func (o *GetBrigadeBadRequest) WithPayload(payload *models.Error) *GetBrigadeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade bad request response
func (o *GetBrigadeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeUnauthorizedCode is the HTTP code returned for type GetBrigadeUnauthorized
const GetBrigadeUnauthorizedCode int = 401

/*
GetBrigadeUnauthorized Unauthorized

swagger:response getBrigadeUnauthorized
*/
type GetBrigadeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeUnauthorized creates GetBrigadeUnauthorized with default headers values
func NewGetBrigadeUnauthorized() *GetBrigadeUnauthorized {

	return &GetBrigadeUnauthorized{}
}

// WithPayload adds the payload to the get brigade unauthorized response
func (o *GetBrigadeUnauthorized) WithPayload(payload *models.Error) *GetBrigadeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade unauthorized response
func (o *GetBrigadeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeInternalServerErrorCode is the HTTP code returned for type GetBrigadeInternalServerError
const GetBrigadeInternalServerErrorCode int = 500

/*
GetBrigadeInternalServerError Internal Server Error

swagger:response getBrigadeInternalServerError
*/
type GetBrigadeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBrigadeInternalServerError creates GetBrigadeInternalServerError with default headers values
func NewGetBrigadeInternalServerError() *GetBrigadeInternalServerError {

	return &GetBrigadeInternalServerError{}
}

// WithPayload adds the payload to the get brigade internal server error response
func (o *GetBrigadeInternalServerError) WithPayload(payload *models.Error) *GetBrigadeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brigade internal server error response
func (o *GetBrigadeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrigadeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBrigadeServiceUnavailableCode is the HTTP code returned for type GetBrigadeServiceUnavailable
const GetBrigadeServiceUnavailableCode int = 503

/*
GetBrigadeServiceUnavailable Service Temporarily Unavailable

swagger:response getBrigadeServiceUnavailable
*/
type GetBrigadeServiceUnavailable struct {
}

// NewGetBrigadeServiceUnavailable creates GetBrigadeServiceUnavailable with default headers values
func NewGetBrigadeServiceUnavailable() *GetBrigadeServiceUnavailable {

	return &GetBrigadeServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetBrigadeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
