// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-server/models"
)

// GetBrigadeHandlerFunc turns a function with the right signature into a get brigade handler
type GetBrigadeHandlerFunc func(GetBrigadeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBrigadeHandlerFunc) Handle(params GetBrigadeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetBrigadeHandler interface for that can handle valid get brigade params
type GetBrigadeHandler interface {
	Handle(GetBrigadeParams, *models.Principal) middleware.Responder
}

// NewGetBrigade creates a new http.Handler for the get brigade operation
func NewGetBrigade(ctx *middleware.Context, handler GetBrigadeHandler) *GetBrigade {
	return &GetBrigade{Context: ctx, Handler: handler}
}

/*
	GetBrigade swagger:route GET /brigade/{brigade_id} getBrigade

Get VPN socket brigade
*/
type GetBrigade struct {
	Context *middleware.Context
	Handler GetBrigadeHandler
}

func (o *GetBrigade) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBrigadeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
