// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Brigade brigade
//
// swagger:model Brigade
type Brigade struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`

	// Brigade name
	// Required: true
	BrigadeName *string `json:"brigade_name"`

	// Free slots
	// Required: true
	FreeSlots *int64 `json:"free_slots"`

	// Max users
	// Required: true
	MaxUsers *int64 `json:"max_users"`

	// Virtual machine zone
	// Required: true
	Zone *string `json:"zone"`
}

// Validate validates this brigade
func (m *Brigade) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBrigadeName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFreeSlots(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxUsers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateZone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Brigade) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("brigade_id", "body", m.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("brigade_id", "body", "uuid", m.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Brigade) validateBrigadeName(formats strfmt.Registry) error {

	if err := validate.Required("brigade_name", "body", m.BrigadeName); err != nil {
		return err
	}

	return nil
}

func (m *Brigade) validateFreeSlots(formats strfmt.Registry) error {

	if err := validate.Required("free_slots", "body", m.FreeSlots); err != nil {
		return err
	}

	return nil
}

func (m *Brigade) validateMaxUsers(formats strfmt.Registry) error {

	if err := validate.Required("max_users", "body", m.MaxUsers); err != nil {
		return err
	}

	return nil
}

func (m *Brigade) validateZone(formats strfmt.Registry) error {

	if err := validate.Required("zone", "body", m.Zone); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this brigade based on context it is used
func (m *Brigade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Brigade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Brigade) UnmarshalBinary(b []byte) error {
	var res Brigade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
