// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateBirgadeRequest create birgade request
//
// swagger:model CreateBirgadeRequest
type CreateBirgadeRequest struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigadeID"`

	// Brigade name
	// Required: true
	BrigadeName *string `json:"brigadeName"`

	// Virtual machine zone
	// Required: true
	Zone *string `json:"zone"`
}

// Validate validates this create birgade request
func (m *CreateBirgadeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBrigadeName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateZone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBirgadeRequest) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("brigadeID", "body", m.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("brigadeID", "body", "uuid", m.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreateBirgadeRequest) validateBrigadeName(formats strfmt.Registry) error {

	if err := validate.Required("brigadeName", "body", m.BrigadeName); err != nil {
		return err
	}

	return nil
}

func (m *CreateBirgadeRequest) validateZone(formats strfmt.Registry) error {

	if err := validate.Required("zone", "body", m.Zone); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create birgade request based on context it is used
func (m *CreateBirgadeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateBirgadeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateBirgadeRequest) UnmarshalBinary(b []byte) error {
	var res CreateBirgadeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
