// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-client/models"
)

// DeleteConfigReader is a Reader for the DeleteConfig structure.
type DeleteConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /config/{config_id}] deleteConfig", response, response.Code())
	}
}

// NewDeleteConfigOK creates a DeleteConfigOK with default headers values
func NewDeleteConfigOK() *DeleteConfigOK {
	return &DeleteConfigOK{}
}

/*
DeleteConfigOK describes a response with status code 200, with default header values.

OK
*/
type DeleteConfigOK struct {
	Payload *models.FreeSlots
}

// IsSuccess returns true when this delete config o k response has a 2xx status code
func (o *DeleteConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete config o k response has a 3xx status code
func (o *DeleteConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete config o k response has a 4xx status code
func (o *DeleteConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete config o k response has a 5xx status code
func (o *DeleteConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete config o k response a status code equal to that given
func (o *DeleteConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete config o k response
func (o *DeleteConfigOK) Code() int {
	return 200
}

func (o *DeleteConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigOK %s", 200, payload)
}

func (o *DeleteConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigOK %s", 200, payload)
}

func (o *DeleteConfigOK) GetPayload() *models.FreeSlots {
	return o.Payload
}

func (o *DeleteConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FreeSlots)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteConfigBadRequest creates a DeleteConfigBadRequest with default headers values
func NewDeleteConfigBadRequest() *DeleteConfigBadRequest {
	return &DeleteConfigBadRequest{}
}

/*
DeleteConfigBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteConfigBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete config bad request response has a 2xx status code
func (o *DeleteConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete config bad request response has a 3xx status code
func (o *DeleteConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete config bad request response has a 4xx status code
func (o *DeleteConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete config bad request response has a 5xx status code
func (o *DeleteConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete config bad request response a status code equal to that given
func (o *DeleteConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete config bad request response
func (o *DeleteConfigBadRequest) Code() int {
	return 400
}

func (o *DeleteConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigBadRequest %s", 400, payload)
}

func (o *DeleteConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigBadRequest %s", 400, payload)
}

func (o *DeleteConfigBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteConfigUnauthorized creates a DeleteConfigUnauthorized with default headers values
func NewDeleteConfigUnauthorized() *DeleteConfigUnauthorized {
	return &DeleteConfigUnauthorized{}
}

/*
DeleteConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteConfigUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete config unauthorized response has a 2xx status code
func (o *DeleteConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete config unauthorized response has a 3xx status code
func (o *DeleteConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete config unauthorized response has a 4xx status code
func (o *DeleteConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete config unauthorized response has a 5xx status code
func (o *DeleteConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete config unauthorized response a status code equal to that given
func (o *DeleteConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete config unauthorized response
func (o *DeleteConfigUnauthorized) Code() int {
	return 401
}

func (o *DeleteConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigUnauthorized %s", 401, payload)
}

func (o *DeleteConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigUnauthorized %s", 401, payload)
}

func (o *DeleteConfigUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteConfigInternalServerError creates a DeleteConfigInternalServerError with default headers values
func NewDeleteConfigInternalServerError() *DeleteConfigInternalServerError {
	return &DeleteConfigInternalServerError{}
}

/*
DeleteConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteConfigInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete config internal server error response has a 2xx status code
func (o *DeleteConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete config internal server error response has a 3xx status code
func (o *DeleteConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete config internal server error response has a 4xx status code
func (o *DeleteConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete config internal server error response has a 5xx status code
func (o *DeleteConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete config internal server error response a status code equal to that given
func (o *DeleteConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete config internal server error response
func (o *DeleteConfigInternalServerError) Code() int {
	return 500
}

func (o *DeleteConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigInternalServerError %s", 500, payload)
}

func (o *DeleteConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigInternalServerError %s", 500, payload)
}

func (o *DeleteConfigInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteConfigServiceUnavailable creates a DeleteConfigServiceUnavailable with default headers values
func NewDeleteConfigServiceUnavailable() *DeleteConfigServiceUnavailable {
	return &DeleteConfigServiceUnavailable{}
}

/*
DeleteConfigServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type DeleteConfigServiceUnavailable struct {
	Payload *models.ServiceTemporarilyUnavailable
}

// IsSuccess returns true when this delete config service unavailable response has a 2xx status code
func (o *DeleteConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete config service unavailable response has a 3xx status code
func (o *DeleteConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete config service unavailable response has a 4xx status code
func (o *DeleteConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete config service unavailable response has a 5xx status code
func (o *DeleteConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete config service unavailable response a status code equal to that given
func (o *DeleteConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete config service unavailable response
func (o *DeleteConfigServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/{config_id}][%d] deleteConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteConfigServiceUnavailable) GetPayload() *models.ServiceTemporarilyUnavailable {
	return o.Payload
}

func (o *DeleteConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceTemporarilyUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
DeleteConfigBody delete config body
swagger:model DeleteConfigBody
*/
type DeleteConfigBody struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`
}

// Validate validates this delete config body
func (o *DeleteConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteConfigBody) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"brigade_id", "body", o.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"brigade_id", "body", "uuid", o.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete config body based on context it is used
func (o *DeleteConfigBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteConfigBody) UnmarshalBinary(b []byte) error {
	var res DeleteConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
