// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-client/models"
)

// GetBrigadeActivityReader is a Reader for the GetBrigadeActivity structure.
type GetBrigadeActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBrigadeActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBrigadeActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBrigadeActivityBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetBrigadeActivityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBrigadeActivityInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetBrigadeActivityServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /brigade/{brigade_id}/activity] getBrigadeActivity", response, response.Code())
	}
}

// NewGetBrigadeActivityOK creates a GetBrigadeActivityOK with default headers values
func NewGetBrigadeActivityOK() *GetBrigadeActivityOK {
	return &GetBrigadeActivityOK{}
}

/*
GetBrigadeActivityOK describes a response with status code 200, with default header values.

OK
*/
type GetBrigadeActivityOK struct {
	Payload models.BrigadeActivity
}

// IsSuccess returns true when this get brigade activity o k response has a 2xx status code
func (o *GetBrigadeActivityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get brigade activity o k response has a 3xx status code
func (o *GetBrigadeActivityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get brigade activity o k response has a 4xx status code
func (o *GetBrigadeActivityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get brigade activity o k response has a 5xx status code
func (o *GetBrigadeActivityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get brigade activity o k response a status code equal to that given
func (o *GetBrigadeActivityOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get brigade activity o k response
func (o *GetBrigadeActivityOK) Code() int {
	return 200
}

func (o *GetBrigadeActivityOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityOK %s", 200, payload)
}

func (o *GetBrigadeActivityOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityOK %s", 200, payload)
}

func (o *GetBrigadeActivityOK) GetPayload() models.BrigadeActivity {
	return o.Payload
}

func (o *GetBrigadeActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBrigadeActivityBadRequest creates a GetBrigadeActivityBadRequest with default headers values
func NewGetBrigadeActivityBadRequest() *GetBrigadeActivityBadRequest {
	return &GetBrigadeActivityBadRequest{}
}

/*
GetBrigadeActivityBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBrigadeActivityBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get brigade activity bad request response has a 2xx status code
func (o *GetBrigadeActivityBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get brigade activity bad request response has a 3xx status code
func (o *GetBrigadeActivityBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get brigade activity bad request response has a 4xx status code
func (o *GetBrigadeActivityBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get brigade activity bad request response has a 5xx status code
func (o *GetBrigadeActivityBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get brigade activity bad request response a status code equal to that given
func (o *GetBrigadeActivityBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get brigade activity bad request response
func (o *GetBrigadeActivityBadRequest) Code() int {
	return 400
}

func (o *GetBrigadeActivityBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityBadRequest %s", 400, payload)
}

func (o *GetBrigadeActivityBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityBadRequest %s", 400, payload)
}

func (o *GetBrigadeActivityBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBrigadeActivityBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBrigadeActivityUnauthorized creates a GetBrigadeActivityUnauthorized with default headers values
func NewGetBrigadeActivityUnauthorized() *GetBrigadeActivityUnauthorized {
	return &GetBrigadeActivityUnauthorized{}
}

/*
GetBrigadeActivityUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetBrigadeActivityUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get brigade activity unauthorized response has a 2xx status code
func (o *GetBrigadeActivityUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get brigade activity unauthorized response has a 3xx status code
func (o *GetBrigadeActivityUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get brigade activity unauthorized response has a 4xx status code
func (o *GetBrigadeActivityUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get brigade activity unauthorized response has a 5xx status code
func (o *GetBrigadeActivityUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get brigade activity unauthorized response a status code equal to that given
func (o *GetBrigadeActivityUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get brigade activity unauthorized response
func (o *GetBrigadeActivityUnauthorized) Code() int {
	return 401
}

func (o *GetBrigadeActivityUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityUnauthorized %s", 401, payload)
}

func (o *GetBrigadeActivityUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityUnauthorized %s", 401, payload)
}

func (o *GetBrigadeActivityUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBrigadeActivityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBrigadeActivityInternalServerError creates a GetBrigadeActivityInternalServerError with default headers values
func NewGetBrigadeActivityInternalServerError() *GetBrigadeActivityInternalServerError {
	return &GetBrigadeActivityInternalServerError{}
}

/*
GetBrigadeActivityInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBrigadeActivityInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get brigade activity internal server error response has a 2xx status code
func (o *GetBrigadeActivityInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get brigade activity internal server error response has a 3xx status code
func (o *GetBrigadeActivityInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get brigade activity internal server error response has a 4xx status code
func (o *GetBrigadeActivityInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get brigade activity internal server error response has a 5xx status code
func (o *GetBrigadeActivityInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get brigade activity internal server error response a status code equal to that given
func (o *GetBrigadeActivityInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get brigade activity internal server error response
func (o *GetBrigadeActivityInternalServerError) Code() int {
	return 500
}

func (o *GetBrigadeActivityInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityInternalServerError %s", 500, payload)
}

func (o *GetBrigadeActivityInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityInternalServerError %s", 500, payload)
}

func (o *GetBrigadeActivityInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBrigadeActivityInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBrigadeActivityServiceUnavailable creates a GetBrigadeActivityServiceUnavailable with default headers values
func NewGetBrigadeActivityServiceUnavailable() *GetBrigadeActivityServiceUnavailable {
	return &GetBrigadeActivityServiceUnavailable{}
}

/*
GetBrigadeActivityServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type GetBrigadeActivityServiceUnavailable struct {
}

// IsSuccess returns true when this get brigade activity service unavailable response has a 2xx status code
func (o *GetBrigadeActivityServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get brigade activity service unavailable response has a 3xx status code
func (o *GetBrigadeActivityServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get brigade activity service unavailable response has a 4xx status code
func (o *GetBrigadeActivityServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get brigade activity service unavailable response has a 5xx status code
func (o *GetBrigadeActivityServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get brigade activity service unavailable response a status code equal to that given
func (o *GetBrigadeActivityServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get brigade activity service unavailable response
func (o *GetBrigadeActivityServiceUnavailable) Code() int {
	return 503
}

func (o *GetBrigadeActivityServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityServiceUnavailable", 503)
}

func (o *GetBrigadeActivityServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /brigade/{brigade_id}/activity][%d] getBrigadeActivityServiceUnavailable", 503)
}

func (o *GetBrigadeActivityServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
