// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// BlockConfigReader is a Reader for the BlockConfig structure.
type BlockConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BlockConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBlockConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBlockConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewBlockConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBlockConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBlockConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewBlockConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /config/{config_id}/block] blockConfig", response, response.Code())
	}
}

// NewBlockConfigOK creates a BlockConfigOK with default headers values
func NewBlockConfigOK() *BlockConfigOK {
	return &BlockConfigOK{}
}

/*
BlockConfigOK describes a response with status code 200, with default header values.

OK
*/
type BlockConfigOK struct {
	Payload *models.FreeSlots
}

// IsSuccess returns true when this block config o k response has a 2xx status code
func (o *BlockConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this block config o k response has a 3xx status code
func (o *BlockConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config o k response has a 4xx status code
func (o *BlockConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this block config o k response has a 5xx status code
func (o *BlockConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this block config o k response a status code equal to that given
func (o *BlockConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the block config o k response
func (o *BlockConfigOK) Code() int {
	return 200
}

func (o *BlockConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigOK %s", 200, payload)
}

func (o *BlockConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigOK %s", 200, payload)
}

func (o *BlockConfigOK) GetPayload() *models.FreeSlots {
	return o.Payload
}

func (o *BlockConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FreeSlots)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockConfigBadRequest creates a BlockConfigBadRequest with default headers values
func NewBlockConfigBadRequest() *BlockConfigBadRequest {
	return &BlockConfigBadRequest{}
}

/*
BlockConfigBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type BlockConfigBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this block config bad request response has a 2xx status code
func (o *BlockConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this block config bad request response has a 3xx status code
func (o *BlockConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config bad request response has a 4xx status code
func (o *BlockConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this block config bad request response has a 5xx status code
func (o *BlockConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this block config bad request response a status code equal to that given
func (o *BlockConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the block config bad request response
func (o *BlockConfigBadRequest) Code() int {
	return 400
}

func (o *BlockConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigBadRequest %s", 400, payload)
}

func (o *BlockConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigBadRequest %s", 400, payload)
}

func (o *BlockConfigBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *BlockConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockConfigUnauthorized creates a BlockConfigUnauthorized with default headers values
func NewBlockConfigUnauthorized() *BlockConfigUnauthorized {
	return &BlockConfigUnauthorized{}
}

/*
BlockConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type BlockConfigUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this block config unauthorized response has a 2xx status code
func (o *BlockConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this block config unauthorized response has a 3xx status code
func (o *BlockConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config unauthorized response has a 4xx status code
func (o *BlockConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this block config unauthorized response has a 5xx status code
func (o *BlockConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this block config unauthorized response a status code equal to that given
func (o *BlockConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the block config unauthorized response
func (o *BlockConfigUnauthorized) Code() int {
	return 401
}

func (o *BlockConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigUnauthorized %s", 401, payload)
}

func (o *BlockConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigUnauthorized %s", 401, payload)
}

func (o *BlockConfigUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *BlockConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockConfigNotFound creates a BlockConfigNotFound with default headers values
func NewBlockConfigNotFound() *BlockConfigNotFound {
	return &BlockConfigNotFound{}
}

/*
BlockConfigNotFound describes a response with status code 404, with default header values.

Not Found
*/
type BlockConfigNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this block config not found response has a 2xx status code
func (o *BlockConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this block config not found response has a 3xx status code
func (o *BlockConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config not found response has a 4xx status code
func (o *BlockConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this block config not found response has a 5xx status code
func (o *BlockConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this block config not found response a status code equal to that given
func (o *BlockConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the block config not found response
func (o *BlockConfigNotFound) Code() int {
	return 404
}

func (o *BlockConfigNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigNotFound %s", 404, payload)
}

func (o *BlockConfigNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigNotFound %s", 404, payload)
}

func (o *BlockConfigNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *BlockConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockConfigInternalServerError creates a BlockConfigInternalServerError with default headers values
func NewBlockConfigInternalServerError() *BlockConfigInternalServerError {
	return &BlockConfigInternalServerError{}
}

/*
BlockConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type BlockConfigInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this block config internal server error response has a 2xx status code
func (o *BlockConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this block config internal server error response has a 3xx status code
func (o *BlockConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config internal server error response has a 4xx status code
func (o *BlockConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this block config internal server error response has a 5xx status code
func (o *BlockConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this block config internal server error response a status code equal to that given
func (o *BlockConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the block config internal server error response
func (o *BlockConfigInternalServerError) Code() int {
	return 500
}

func (o *BlockConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigInternalServerError %s", 500, payload)
}

func (o *BlockConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigInternalServerError %s", 500, payload)
}

func (o *BlockConfigInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *BlockConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockConfigServiceUnavailable creates a BlockConfigServiceUnavailable with default headers values
func NewBlockConfigServiceUnavailable() *BlockConfigServiceUnavailable {
	return &BlockConfigServiceUnavailable{}
}

/*
BlockConfigServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type BlockConfigServiceUnavailable struct {
	Payload *models.ServiceTemporarilyUnavailable
}

// IsSuccess returns true when this block config service unavailable response has a 2xx status code
func (o *BlockConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this block config service unavailable response has a 3xx status code
func (o *BlockConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block config service unavailable response has a 4xx status code
func (o *BlockConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this block config service unavailable response has a 5xx status code
func (o *BlockConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this block config service unavailable response a status code equal to that given
func (o *BlockConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the block config service unavailable response
func (o *BlockConfigServiceUnavailable) Code() int {
	return 503
}

func (o *BlockConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigServiceUnavailable %s", 503, payload)
}

func (o *BlockConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/block][%d] blockConfigServiceUnavailable %s", 503, payload)
}

func (o *BlockConfigServiceUnavailable) GetPayload() *models.ServiceTemporarilyUnavailable {
	return o.Payload
}

func (o *BlockConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceTemporarilyUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
BlockConfigBody block config body
swagger:model BlockConfigBody
*/
type BlockConfigBody struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`
}

// Validate validates this block config body
func (o *BlockConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BlockConfigBody) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"brigade_id", "body", o.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"brigade_id", "body", "uuid", o.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this block config body based on context it is used
func (o *BlockConfigBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *BlockConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BlockConfigBody) UnmarshalBinary(b []byte) error {
	var res BlockConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
