// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBrigadeSlotsParams creates a new GetBrigadeSlotsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBrigadeSlotsParams() *GetBrigadeSlotsParams {
	return &GetBrigadeSlotsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBrigadeSlotsParamsWithTimeout creates a new GetBrigadeSlotsParams object
// with the ability to set a timeout on a request.
func NewGetBrigadeSlotsParamsWithTimeout(timeout time.Duration) *GetBrigadeSlotsParams {
	return &GetBrigadeSlotsParams{
		timeout: timeout,
	}
}

// NewGetBrigadeSlotsParamsWithContext creates a new GetBrigadeSlotsParams object
// with the ability to set a context for a request.
func NewGetBrigadeSlotsParamsWithContext(ctx context.Context) *GetBrigadeSlotsParams {
	return &GetBrigadeSlotsParams{
		Context: ctx,
	}
}

// NewGetBrigadeSlotsParamsWithHTTPClient creates a new GetBrigadeSlotsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBrigadeSlotsParamsWithHTTPClient(client *http.Client) *GetBrigadeSlotsParams {
	return &GetBrigadeSlotsParams{
		HTTPClient: client,
	}
}

/*
GetBrigadeSlotsParams contains all the parameters to send to the API endpoint

	for the get brigade slots operation.

	Typically these are written to a http.Request.
*/
type GetBrigadeSlotsParams struct {

	/* BrigadeID.

	   Brigade ID
	*/
	BrigadeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get brigade slots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrigadeSlotsParams) WithDefaults() *GetBrigadeSlotsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get brigade slots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrigadeSlotsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get brigade slots params
func (o *GetBrigadeSlotsParams) WithTimeout(timeout time.Duration) *GetBrigadeSlotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get brigade slots params
func (o *GetBrigadeSlotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get brigade slots params
func (o *GetBrigadeSlotsParams) WithContext(ctx context.Context) *GetBrigadeSlotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get brigade slots params
func (o *GetBrigadeSlotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get brigade slots params
func (o *GetBrigadeSlotsParams) WithHTTPClient(client *http.Client) *GetBrigadeSlotsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get brigade slots params
func (o *GetBrigadeSlotsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrigadeID adds the brigadeID to the get brigade slots params
func (o *GetBrigadeSlotsParams) WithBrigadeID(brigadeID string) *GetBrigadeSlotsParams {
	o.SetBrigadeID(brigadeID)
	return o
}

// SetBrigadeID adds the brigadeId to the get brigade slots params
func (o *GetBrigadeSlotsParams) SetBrigadeID(brigadeID string) {
	o.BrigadeID = brigadeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetBrigadeSlotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brigade_id
	if err := r.SetPathParam("brigade_id", o.BrigadeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
