// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBrigadeActivityParams creates a new GetBrigadeActivityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBrigadeActivityParams() *GetBrigadeActivityParams {
	return &GetBrigadeActivityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBrigadeActivityParamsWithTimeout creates a new GetBrigadeActivityParams object
// with the ability to set a timeout on a request.
func NewGetBrigadeActivityParamsWithTimeout(timeout time.Duration) *GetBrigadeActivityParams {
	return &GetBrigadeActivityParams{
		timeout: timeout,
	}
}

// NewGetBrigadeActivityParamsWithContext creates a new GetBrigadeActivityParams object
// with the ability to set a context for a request.
func NewGetBrigadeActivityParamsWithContext(ctx context.Context) *GetBrigadeActivityParams {
	return &GetBrigadeActivityParams{
		Context: ctx,
	}
}

// NewGetBrigadeActivityParamsWithHTTPClient creates a new GetBrigadeActivityParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBrigadeActivityParamsWithHTTPClient(client *http.Client) *GetBrigadeActivityParams {
	return &GetBrigadeActivityParams{
		HTTPClient: client,
	}
}

/*
GetBrigadeActivityParams contains all the parameters to send to the API endpoint

	for the get brigade activity operation.

	Typically these are written to a http.Request.
*/
type GetBrigadeActivityParams struct {

	/* BrigadeID.

	   Brigade ID
	*/
	BrigadeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get brigade activity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrigadeActivityParams) WithDefaults() *GetBrigadeActivityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get brigade activity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrigadeActivityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get brigade activity params
func (o *GetBrigadeActivityParams) WithTimeout(timeout time.Duration) *GetBrigadeActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get brigade activity params
func (o *GetBrigadeActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get brigade activity params
func (o *GetBrigadeActivityParams) WithContext(ctx context.Context) *GetBrigadeActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get brigade activity params
func (o *GetBrigadeActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get brigade activity params
func (o *GetBrigadeActivityParams) WithHTTPClient(client *http.Client) *GetBrigadeActivityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get brigade activity params
func (o *GetBrigadeActivityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrigadeID adds the brigadeID to the get brigade activity params
func (o *GetBrigadeActivityParams) WithBrigadeID(brigadeID string) *GetBrigadeActivityParams {
	o.SetBrigadeID(brigadeID)
	return o
}

// SetBrigadeID adds the brigadeId to the get brigade activity params
func (o *GetBrigadeActivityParams) SetBrigadeID(brigadeID string) {
	o.BrigadeID = brigadeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetBrigadeActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brigade_id
	if err := r.SetPathParam("brigade_id", o.BrigadeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
