// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// UnblockConfigReader is a Reader for the UnblockConfig structure.
type UnblockConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnblockConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnblockConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnblockConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUnblockConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUnblockConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUnblockConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUnblockConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /config/{config_id}/unblock] unblockConfig", response, response.Code())
	}
}

// NewUnblockConfigOK creates a UnblockConfigOK with default headers values
func NewUnblockConfigOK() *UnblockConfigOK {
	return &UnblockConfigOK{}
}

/*
UnblockConfigOK describes a response with status code 200, with default header values.

OK
*/
type UnblockConfigOK struct {
	Payload *models.FreeSlots
}

// IsSuccess returns true when this unblock config o k response has a 2xx status code
func (o *UnblockConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unblock config o k response has a 3xx status code
func (o *UnblockConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config o k response has a 4xx status code
func (o *UnblockConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this unblock config o k response has a 5xx status code
func (o *UnblockConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this unblock config o k response a status code equal to that given
func (o *UnblockConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the unblock config o k response
func (o *UnblockConfigOK) Code() int {
	return 200
}

func (o *UnblockConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigOK %s", 200, payload)
}

func (o *UnblockConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigOK %s", 200, payload)
}

func (o *UnblockConfigOK) GetPayload() *models.FreeSlots {
	return o.Payload
}

func (o *UnblockConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FreeSlots)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnblockConfigBadRequest creates a UnblockConfigBadRequest with default headers values
func NewUnblockConfigBadRequest() *UnblockConfigBadRequest {
	return &UnblockConfigBadRequest{}
}

/*
UnblockConfigBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UnblockConfigBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this unblock config bad request response has a 2xx status code
func (o *UnblockConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unblock config bad request response has a 3xx status code
func (o *UnblockConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config bad request response has a 4xx status code
func (o *UnblockConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this unblock config bad request response has a 5xx status code
func (o *UnblockConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this unblock config bad request response a status code equal to that given
func (o *UnblockConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the unblock config bad request response
func (o *UnblockConfigBadRequest) Code() int {
	return 400
}

func (o *UnblockConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigBadRequest %s", 400, payload)
}

func (o *UnblockConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigBadRequest %s", 400, payload)
}

func (o *UnblockConfigBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnblockConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnblockConfigUnauthorized creates a UnblockConfigUnauthorized with default headers values
func NewUnblockConfigUnauthorized() *UnblockConfigUnauthorized {
	return &UnblockConfigUnauthorized{}
}

/*
UnblockConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UnblockConfigUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this unblock config unauthorized response has a 2xx status code
func (o *UnblockConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unblock config unauthorized response has a 3xx status code
func (o *UnblockConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config unauthorized response has a 4xx status code
func (o *UnblockConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this unblock config unauthorized response has a 5xx status code
func (o *UnblockConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this unblock config unauthorized response a status code equal to that given
func (o *UnblockConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the unblock config unauthorized response
func (o *UnblockConfigUnauthorized) Code() int {
	return 401
}

func (o *UnblockConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigUnauthorized %s", 401, payload)
}

func (o *UnblockConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigUnauthorized %s", 401, payload)
}

func (o *UnblockConfigUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnblockConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnblockConfigNotFound creates a UnblockConfigNotFound with default headers values
func NewUnblockConfigNotFound() *UnblockConfigNotFound {
	return &UnblockConfigNotFound{}
}

/*
UnblockConfigNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UnblockConfigNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this unblock config not found response has a 2xx status code
func (o *UnblockConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unblock config not found response has a 3xx status code
func (o *UnblockConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config not found response has a 4xx status code
func (o *UnblockConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this unblock config not found response has a 5xx status code
func (o *UnblockConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this unblock config not found response a status code equal to that given
func (o *UnblockConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the unblock config not found response
func (o *UnblockConfigNotFound) Code() int {
	return 404
}

func (o *UnblockConfigNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigNotFound %s", 404, payload)
}

func (o *UnblockConfigNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigNotFound %s", 404, payload)
}

func (o *UnblockConfigNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnblockConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnblockConfigInternalServerError creates a UnblockConfigInternalServerError with default headers values
func NewUnblockConfigInternalServerError() *UnblockConfigInternalServerError {
	return &UnblockConfigInternalServerError{}
}

/*
UnblockConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UnblockConfigInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this unblock config internal server error response has a 2xx status code
func (o *UnblockConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unblock config internal server error response has a 3xx status code
func (o *UnblockConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config internal server error response has a 4xx status code
func (o *UnblockConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this unblock config internal server error response has a 5xx status code
func (o *UnblockConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this unblock config internal server error response a status code equal to that given
func (o *UnblockConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the unblock config internal server error response
func (o *UnblockConfigInternalServerError) Code() int {
	return 500
}

func (o *UnblockConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigInternalServerError %s", 500, payload)
}

func (o *UnblockConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigInternalServerError %s", 500, payload)
}

func (o *UnblockConfigInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnblockConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnblockConfigServiceUnavailable creates a UnblockConfigServiceUnavailable with default headers values
func NewUnblockConfigServiceUnavailable() *UnblockConfigServiceUnavailable {
	return &UnblockConfigServiceUnavailable{}
}

/*
UnblockConfigServiceUnavailable describes a response with status code 503, with default header values.

Service Temporarily Unavailable
*/
type UnblockConfigServiceUnavailable struct {
	Payload *models.ServiceTemporarilyUnavailable
}

// IsSuccess returns true when this unblock config service unavailable response has a 2xx status code
func (o *UnblockConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unblock config service unavailable response has a 3xx status code
func (o *UnblockConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unblock config service unavailable response has a 4xx status code
func (o *UnblockConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this unblock config service unavailable response has a 5xx status code
func (o *UnblockConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this unblock config service unavailable response a status code equal to that given
func (o *UnblockConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the unblock config service unavailable response
func (o *UnblockConfigServiceUnavailable) Code() int {
	return 503
}

func (o *UnblockConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigServiceUnavailable %s", 503, payload)
}

func (o *UnblockConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /config/{config_id}/unblock][%d] unblockConfigServiceUnavailable %s", 503, payload)
}

func (o *UnblockConfigServiceUnavailable) GetPayload() *models.ServiceTemporarilyUnavailable {
	return o.Payload
}

func (o *UnblockConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceTemporarilyUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UnblockConfigBody unblock config body
swagger:model UnblockConfigBody
*/
type UnblockConfigBody struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`
}

// Validate validates this unblock config body
func (o *UnblockConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UnblockConfigBody) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"brigade_id", "body", o.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"brigade_id", "body", "uuid", o.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this unblock config body based on context it is used
func (o *UnblockConfigBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UnblockConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UnblockConfigBody) UnmarshalBinary(b []byte) error {
	var res UnblockConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
