// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-cli/models"
)

// Schema cli for Brigade

// register flags to command
func registerModelBrigadeFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerBrigadePropBrigadeID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBrigadePropBrigadeName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBrigadePropDeleted(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBrigadePropMaxUsers(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBrigadePropZone(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerBrigadePropBrigadeID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBrigadeIDDescription := `Required. Brigade ID`

	var flagBrigadeIDName string
	if cmdPrefix == "" {
		flagBrigadeIDName = "brigadeID"
	} else {
		flagBrigadeIDName = fmt.Sprintf("%v.brigadeID", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBrigadeIDName, "", flagBrigadeIDDescription)

	return nil
}

func registerBrigadePropBrigadeName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBrigadeNameDescription := `Required. Brigade name`

	var flagBrigadeNameName string
	if cmdPrefix == "" {
		flagBrigadeNameName = "brigadeName"
	} else {
		flagBrigadeNameName = fmt.Sprintf("%v.brigadeName", cmdPrefix)
	}

	var flagBrigadeNameDefault string

	_ = cmd.PersistentFlags().String(flagBrigadeNameName, flagBrigadeNameDefault, flagBrigadeNameDescription)

	return nil
}

func registerBrigadePropDeleted(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDeletedDescription := `Required. Deleted`

	var flagDeletedName string
	if cmdPrefix == "" {
		flagDeletedName = "deleted"
	} else {
		flagDeletedName = fmt.Sprintf("%v.deleted", cmdPrefix)
	}

	var flagDeletedDefault bool

	_ = cmd.PersistentFlags().Bool(flagDeletedName, flagDeletedDefault, flagDeletedDescription)

	return nil
}

func registerBrigadePropMaxUsers(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMaxUsersDescription := `Required. Max users`

	var flagMaxUsersName string
	if cmdPrefix == "" {
		flagMaxUsersName = "maxUsers"
	} else {
		flagMaxUsersName = fmt.Sprintf("%v.maxUsers", cmdPrefix)
	}

	var flagMaxUsersDefault int64

	_ = cmd.PersistentFlags().Int64(flagMaxUsersName, flagMaxUsersDefault, flagMaxUsersDescription)

	return nil
}

func registerBrigadePropZone(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagZoneDescription := `Required. Virtual machine zone`

	var flagZoneName string
	if cmdPrefix == "" {
		flagZoneName = "zone"
	} else {
		flagZoneName = fmt.Sprintf("%v.zone", cmdPrefix)
	}

	var flagZoneDefault string

	_ = cmd.PersistentFlags().String(flagZoneName, flagZoneDefault, flagZoneDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelBrigadeFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, BrigadeIDAdded := retrieveBrigadePropBrigadeIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BrigadeIDAdded

	err, BrigadeNameAdded := retrieveBrigadePropBrigadeNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BrigadeNameAdded

	err, DeletedAdded := retrieveBrigadePropDeletedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DeletedAdded

	err, MaxUsersAdded := retrieveBrigadePropMaxUsersFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MaxUsersAdded

	err, ZoneAdded := retrieveBrigadePropZoneFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ZoneAdded

	return nil, retAdded
}

func retrieveBrigadePropBrigadeIDFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBrigadeIDName := fmt.Sprintf("%v.brigadeID", cmdPrefix)
	if cmd.Flags().Changed(flagBrigadeIDName) {

		var flagBrigadeIDName string
		if cmdPrefix == "" {
			flagBrigadeIDName = "brigadeID"
		} else {
			flagBrigadeIDName = fmt.Sprintf("%v.brigadeID", cmdPrefix)
		}

		flagBrigadeIDValueStr, err := cmd.Flags().GetString(flagBrigadeIDName)
		if err != nil {
			return err, false
		}
		var flagBrigadeIDValue strfmt.UUID
		if err := flagBrigadeIDValue.UnmarshalText([]byte(flagBrigadeIDValueStr)); err != nil {
			return err, false
		}
		m.BrigadeID = &flagBrigadeIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBrigadePropBrigadeNameFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBrigadeNameName := fmt.Sprintf("%v.brigadeName", cmdPrefix)
	if cmd.Flags().Changed(flagBrigadeNameName) {

		var flagBrigadeNameName string
		if cmdPrefix == "" {
			flagBrigadeNameName = "brigadeName"
		} else {
			flagBrigadeNameName = fmt.Sprintf("%v.brigadeName", cmdPrefix)
		}

		flagBrigadeNameValue, err := cmd.Flags().GetString(flagBrigadeNameName)
		if err != nil {
			return err, false
		}
		m.BrigadeName = &flagBrigadeNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBrigadePropDeletedFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDeletedName := fmt.Sprintf("%v.deleted", cmdPrefix)
	if cmd.Flags().Changed(flagDeletedName) {

		var flagDeletedName string
		if cmdPrefix == "" {
			flagDeletedName = "deleted"
		} else {
			flagDeletedName = fmt.Sprintf("%v.deleted", cmdPrefix)
		}

		flagDeletedValue, err := cmd.Flags().GetBool(flagDeletedName)
		if err != nil {
			return err, false
		}
		m.Deleted = &flagDeletedValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBrigadePropMaxUsersFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMaxUsersName := fmt.Sprintf("%v.maxUsers", cmdPrefix)
	if cmd.Flags().Changed(flagMaxUsersName) {

		var flagMaxUsersName string
		if cmdPrefix == "" {
			flagMaxUsersName = "maxUsers"
		} else {
			flagMaxUsersName = fmt.Sprintf("%v.maxUsers", cmdPrefix)
		}

		flagMaxUsersValue, err := cmd.Flags().GetInt64(flagMaxUsersName)
		if err != nil {
			return err, false
		}
		m.MaxUsers = &flagMaxUsersValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBrigadePropZoneFlags(depth int, m *models.Brigade, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagZoneName := fmt.Sprintf("%v.zone", cmdPrefix)
	if cmd.Flags().Changed(flagZoneName) {

		var flagZoneName string
		if cmdPrefix == "" {
			flagZoneName = "zone"
		} else {
			flagZoneName = fmt.Sprintf("%v.zone", cmdPrefix)
		}

		flagZoneValue, err := cmd.Flags().GetString(flagZoneName)
		if err != nil {
			return err, false
		}
		m.Zone = &flagZoneValue

		retAdded = true
	}

	return nil, retAdded
}
