// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-cli/models"
)

// Schema cli for OrderStatus

// register flags to command
func registerModelOrderStatusFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerOrderStatusPropMessage(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerOrderStatusPropOrderID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerOrderStatusPropRetryAfter(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerOrderStatusPropStatus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerOrderStatusPropMessage(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMessageDescription := `Required. Message`

	var flagMessageName string
	if cmdPrefix == "" {
		flagMessageName = "message"
	} else {
		flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
	}

	var flagMessageDefault string

	_ = cmd.PersistentFlags().String(flagMessageName, flagMessageDefault, flagMessageDescription)

	return nil
}

func registerOrderStatusPropOrderID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagOrderIDDescription := `Order ID`

	var flagOrderIDName string
	if cmdPrefix == "" {
		flagOrderIDName = "order_id"
	} else {
		flagOrderIDName = fmt.Sprintf("%v.order_id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagOrderIDName, "", flagOrderIDDescription)

	return nil
}

func registerOrderStatusPropRetryAfter(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRetryAfterDescription := `Retry after seconds`

	var flagRetryAfterName string
	if cmdPrefix == "" {
		flagRetryAfterName = "retryAfter"
	} else {
		flagRetryAfterName = fmt.Sprintf("%v.retryAfter", cmdPrefix)
	}

	var flagRetryAfterDefault int64

	_ = cmd.PersistentFlags().Int64(flagRetryAfterName, flagRetryAfterDefault, flagRetryAfterDescription)

	return nil
}

func registerOrderStatusPropStatus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStatusDescription := `Enum: ["created","processing","completed","failed"]. Required. Order status`

	var flagStatusName string
	if cmdPrefix == "" {
		flagStatusName = "status"
	} else {
		flagStatusName = fmt.Sprintf("%v.status", cmdPrefix)
	}

	var flagStatusDefault string

	_ = cmd.PersistentFlags().String(flagStatusName, flagStatusDefault, flagStatusDescription)

	if err := cmd.RegisterFlagCompletionFunc(flagStatusName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["created","processing","completed","failed"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelOrderStatusFlags(depth int, m *models.OrderStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, MessageAdded := retrieveOrderStatusPropMessageFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MessageAdded

	err, OrderIDAdded := retrieveOrderStatusPropOrderIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || OrderIDAdded

	err, RetryAfterAdded := retrieveOrderStatusPropRetryAfterFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RetryAfterAdded

	err, StatusAdded := retrieveOrderStatusPropStatusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StatusAdded

	return nil, retAdded
}

func retrieveOrderStatusPropMessageFlags(depth int, m *models.OrderStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMessageName := fmt.Sprintf("%v.message", cmdPrefix)
	if cmd.Flags().Changed(flagMessageName) {

		var flagMessageName string
		if cmdPrefix == "" {
			flagMessageName = "message"
		} else {
			flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
		}

		flagMessageValue, err := cmd.Flags().GetString(flagMessageName)
		if err != nil {
			return err, false
		}
		m.Message = &flagMessageValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveOrderStatusPropOrderIDFlags(depth int, m *models.OrderStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagOrderIDName := fmt.Sprintf("%v.order_id", cmdPrefix)
	if cmd.Flags().Changed(flagOrderIDName) {

		var flagOrderIDName string
		if cmdPrefix == "" {
			flagOrderIDName = "order_id"
		} else {
			flagOrderIDName = fmt.Sprintf("%v.order_id", cmdPrefix)
		}

		flagOrderIDValueStr, err := cmd.Flags().GetString(flagOrderIDName)
		if err != nil {
			return err, false
		}
		var flagOrderIDValue strfmt.UUID
		if err := flagOrderIDValue.UnmarshalText([]byte(flagOrderIDValueStr)); err != nil {
			return err, false
		}
		m.OrderID = flagOrderIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveOrderStatusPropRetryAfterFlags(depth int, m *models.OrderStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRetryAfterName := fmt.Sprintf("%v.retryAfter", cmdPrefix)
	if cmd.Flags().Changed(flagRetryAfterName) {

		var flagRetryAfterName string
		if cmdPrefix == "" {
			flagRetryAfterName = "retryAfter"
		} else {
			flagRetryAfterName = fmt.Sprintf("%v.retryAfter", cmdPrefix)
		}

		flagRetryAfterValue, err := cmd.Flags().GetInt64(flagRetryAfterName)
		if err != nil {
			return err, false
		}
		m.RetryAfter = flagRetryAfterValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveOrderStatusPropStatusFlags(depth int, m *models.OrderStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStatusName := fmt.Sprintf("%v.status", cmdPrefix)
	if cmd.Flags().Changed(flagStatusName) {

		var flagStatusName string
		if cmdPrefix == "" {
			flagStatusName = "status"
		} else {
			flagStatusName = fmt.Sprintf("%v.status", cmdPrefix)
		}

		flagStatusValue, err := cmd.Flags().GetString(flagStatusName)
		if err != nil {
			return err, false
		}
		m.Status = &flagStatusValue

		retAdded = true
	}

	return nil, retAdded
}
