BEGIN;

SELECT _v.assert_user_is_superuser();

SELECT _v.register_patch( '026-vgs-roles', ARRAY[ '001-init', '002-roles', '003-stats', '004-stats', '005-stats', '006-stats', '007-stats', '008-domains', '009-domains', '010-viewfixes', '011-collectsnaps', '012-brigades-instance', '013-slot-flags', '014-viewfixes', '015-stats', '016-viewfixes', '017-viewfixes', '018-viewfixes', '019-ctrl-keys', '020-viewfixes', '021-vgmigr-role', '022-fix-brigades', '023-fix-brigades2', '024-fix-stats', '025-orders']);

CREATE ROLE vgs_admin WITH LOGIN;

GRANT USAGE ON SCHEMA pairs TO vgs_admin;
GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA pairs TO vgs_admin;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA pairs TO vgs_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA "pairs" GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO vgs_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA "pairs" GRANT SELECT,UPDATE ON SEQUENCES TO vgs_admin;

GRANT USAGE ON SCHEMA brigades TO vgs_admin;
GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA brigades TO vgs_admin;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA brigades TO vgs_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA "brigades" GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO vgs_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA "brigades" GRANT SELECT,UPDATE ON SEQUENCES TO vgs_admin;

GRANT USAGE ON SCHEMA stats TO vgs_admin;
GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA stats TO vgs_admin;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA stats TO vgs_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA "stats" GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO vgs_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA "stats" GRANT SELECT,UPDATE ON SEQUENCES TO vgs_admin;

CREATE ROLE vgs_user WITH LOGIN;

GRANT USAGE ON SCHEMA pairs TO vgs_user;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA pairs TO vgs_user;
GRANT SELECT ON ALL TABLES IN SCHEMA pairs TO vgs_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA "pairs" GRANT SELECT ON TABLES TO vgs_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "pairs" GRANT SELECT ON SEQUENCES TO vgs_user;

GRANT USAGE ON SCHEMA brigades TO vgs_user;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA brigades TO vgs_user;
GRANT SELECT ON ALL TABLES IN SCHEMA brigades TO vgs_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA "brigades" GRANT SELECT ON TABLES TO vgs_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "brigades" GRANT SELECT ON SEQUENCES TO vgs_user;

GRANT USAGE ON SCHEMA stats TO vgs_user;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA stats TO vgs_user;
GRANT SELECT ON ALL TABLES IN SCHEMA stats TO vgs_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA "stats" GRANT SELECT ON TABLES TO vgs_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "stats" GRANT SELECT ON SEQUENCES TO vgs_user;


COMMIT;