// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ConfigType VPN config type
//
// swagger:model ConfigType
type ConfigType string

func NewConfigType(value ConfigType) *ConfigType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ConfigType.
func (m ConfigType) Pointer() *ConfigType {
	return &m
}

const (

	// ConfigTypeWireguard captures enum value "wireguard"
	ConfigTypeWireguard ConfigType = "wireguard"

	// ConfigTypeOutline captures enum value "outline"
	ConfigTypeOutline ConfigType = "outline"

	// ConfigTypeUniversal captures enum value "universal"
	ConfigTypeUniversal ConfigType = "universal"

	// ConfigTypeProto0 captures enum value "proto0"
	ConfigTypeProto0 ConfigType = "proto0"
)

// for schema
var configTypeEnum []interface{}

func init() {
	var res []ConfigType
	if err := json.Unmarshal([]byte(`["wireguard","outline","universal","proto0"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		configTypeEnum = append(configTypeEnum, v)
	}
}

func (m ConfigType) validateConfigTypeEnum(path, location string, value ConfigType) error {
	if err := validate.EnumCase(path, location, value, configTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this config type
func (m ConfigType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConfigTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this config type based on context it is used
func (m ConfigType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
