// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceTemporarilyUnavailable service temporarily unavailable
//
// swagger:model ServiceTemporarilyUnavailable
type ServiceTemporarilyUnavailable struct {

	// message
	// Required: true
	Message *string `json:"message"`

	// retry after
	// Required: true
	// Format: date-time
	RetryAfter *strfmt.DateTime `json:"retry_after"`
}

// Validate validates this service temporarily unavailable
func (m *ServiceTemporarilyUnavailable) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRetryAfter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceTemporarilyUnavailable) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *ServiceTemporarilyUnavailable) validateRetryAfter(formats strfmt.Registry) error {

	if err := validate.Required("retry_after", "body", m.RetryAfter); err != nil {
		return err
	}

	if err := validate.FormatOf("retry_after", "body", "date-time", m.RetryAfter.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service temporarily unavailable based on context it is used
func (m *ServiceTemporarilyUnavailable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceTemporarilyUnavailable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceTemporarilyUnavailable) UnmarshalBinary(b []byte) error {
	var res ServiceTemporarilyUnavailable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
