// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateConfigRequest create config request
//
// swagger:model CreateConfigRequest
type CreateConfigRequest struct {

	// Brigade ID
	// Required: true
	// Format: uuid
	BrigadeID *strfmt.UUID `json:"brigade_id"`

	// config type
	// Required: true
	ConfigType *ConfigType `json:"config_type"`
}

// Validate validates this create config request
func (m *CreateConfigRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrigadeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfigType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateConfigRequest) validateBrigadeID(formats strfmt.Registry) error {

	if err := validate.Required("brigade_id", "body", m.BrigadeID); err != nil {
		return err
	}

	if err := validate.FormatOf("brigade_id", "body", "uuid", m.BrigadeID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreateConfigRequest) validateConfigType(formats strfmt.Registry) error {

	if err := validate.Required("config_type", "body", m.ConfigType); err != nil {
		return err
	}

	if err := validate.Required("config_type", "body", m.ConfigType); err != nil {
		return err
	}

	if m.ConfigType != nil {
		if err := m.ConfigType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("config_type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("config_type")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create config request based on the context it is used
func (m *CreateConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfigType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateConfigRequest) contextValidateConfigType(ctx context.Context, formats strfmt.Registry) error {

	if m.ConfigType != nil {

		if err := m.ConfigType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("config_type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("config_type")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateConfigRequest) UnmarshalBinary(b []byte) error {
	var res CreateConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
