// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VPNConfigResponse v p n config response
//
// swagger:model VPNConfigResponse
type VPNConfigResponse struct {
	VPNConfig

	FreeSlots
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *VPNConfigResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 VPNConfig
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.VPNConfig = aO0

	// AO1
	var aO1 FreeSlots
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.FreeSlots = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m VPNConfigResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.VPNConfig)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.FreeSlots)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this v p n config response
func (m *VPNConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with VPNConfig
	if err := m.VPNConfig.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with FreeSlots
	if err := m.FreeSlots.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this v p n config response based on the context it is used
func (m *VPNConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with VPNConfig
	if err := m.VPNConfig.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with FreeSlots
	if err := m.FreeSlots.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *VPNConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VPNConfigResponse) UnmarshalBinary(b []byte) error {
	var res VPNConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
