// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WireGuardConfig wire guard config
//
// swagger:model WireGuardConfig
type WireGuardConfig struct {

	// file content
	// Required: true
	FileContent *string `json:"file_content"`

	// file name
	// Required: true
	FileName *string `json:"file_name"`

	// tunnel name
	// Required: true
	TunnelName *string `json:"tunnel_name"`
}

// Validate validates this wire guard config
func (m *WireGuardConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFileContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTunnelName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WireGuardConfig) validateFileContent(formats strfmt.Registry) error {

	if err := validate.Required("file_content", "body", m.FileContent); err != nil {
		return err
	}

	return nil
}

func (m *WireGuardConfig) validateFileName(formats strfmt.Registry) error {

	if err := validate.Required("file_name", "body", m.FileName); err != nil {
		return err
	}

	return nil
}

func (m *WireGuardConfig) validateTunnelName(formats strfmt.Registry) error {

	if err := validate.Required("tunnel_name", "body", m.TunnelName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wire guard config based on context it is used
func (m *WireGuardConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireGuardConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireGuardConfig) UnmarshalBinary(b []byte) error {
	var res WireGuardConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
