// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vpngen/dc-mgmt/api/vgsbrigades/gen-cli/models"
)

// NewCreateBrigadeParams creates a new CreateBrigadeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBrigadeParams() *CreateBrigadeParams {
	return &CreateBrigadeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBrigadeParamsWithTimeout creates a new CreateBrigadeParams object
// with the ability to set a timeout on a request.
func NewCreateBrigadeParamsWithTimeout(timeout time.Duration) *CreateBrigadeParams {
	return &CreateBrigadeParams{
		timeout: timeout,
	}
}

// NewCreateBrigadeParamsWithContext creates a new CreateBrigadeParams object
// with the ability to set a context for a request.
func NewCreateBrigadeParamsWithContext(ctx context.Context) *CreateBrigadeParams {
	return &CreateBrigadeParams{
		Context: ctx,
	}
}

// NewCreateBrigadeParamsWithHTTPClient creates a new CreateBrigadeParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBrigadeParamsWithHTTPClient(client *http.Client) *CreateBrigadeParams {
	return &CreateBrigadeParams{
		HTTPClient: client,
	}
}

/*
CreateBrigadeParams contains all the parameters to send to the API endpoint

	for the create brigade operation.

	Typically these are written to a http.Request.
*/
type CreateBrigadeParams struct {

	/* Body.

	   Brigade data
	*/
	Body *models.CreateBirgadeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create brigade params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBrigadeParams) WithDefaults() *CreateBrigadeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create brigade params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBrigadeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create brigade params
func (o *CreateBrigadeParams) WithTimeout(timeout time.Duration) *CreateBrigadeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create brigade params
func (o *CreateBrigadeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create brigade params
func (o *CreateBrigadeParams) WithContext(ctx context.Context) *CreateBrigadeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create brigade params
func (o *CreateBrigadeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create brigade params
func (o *CreateBrigadeParams) WithHTTPClient(client *http.Client) *CreateBrigadeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create brigade params
func (o *CreateBrigadeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create brigade params
func (o *CreateBrigadeParams) WithBody(body *models.CreateBirgadeRequest) *CreateBrigadeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create brigade params
func (o *CreateBrigadeParams) SetBody(body *models.CreateBirgadeRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBrigadeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
