// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new operations API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new operations API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CheckOrderStatus(params *CheckOrderStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CheckOrderStatusOK, error)

	CreateBrigade(params *CreateBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateBrigadeAccepted, error)

	DeleteBrigade(params *DeleteBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteBrigadeAccepted, error)

	GetBrigade(params *GetBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBrigadeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CheckOrderStatus checks order status
*/
func (a *Client) CheckOrderStatus(params *CheckOrderStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CheckOrderStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckOrderStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkOrderStatus",
		Method:             "GET",
		PathPattern:        "/brigade/status/{order_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckOrderStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckOrderStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for checkOrderStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CreateBrigade creates v p n socket brigade
*/
func (a *Client) CreateBrigade(params *CreateBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateBrigadeAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateBrigadeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createBrigade",
		Method:             "POST",
		PathPattern:        "/brigade",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateBrigadeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateBrigadeAccepted)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createBrigade: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteBrigade deletes v p n socket brigade
*/
func (a *Client) DeleteBrigade(params *DeleteBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteBrigadeAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteBrigadeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteBrigade",
		Method:             "DELETE",
		PathPattern:        "/brigade/{brigade_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteBrigadeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteBrigadeAccepted)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteBrigade: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetBrigade gets v p n socket brigade
*/
func (a *Client) GetBrigade(params *GetBrigadeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBrigadeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBrigadeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBrigade",
		Method:             "GET",
		PathPattern:        "/brigade/{brigade_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBrigadeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBrigadeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getBrigade: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
