---
swagger: '2.0'
info:
  title: VPN Generator socket datacenter  API
  description: VPN Generator socket datacenter  API
  version: 1.0.0

basePath: /v1

paths:

  /config:

    post:
      security:
        - JWT:
          - manager
      summary: Create VPN config
      operationId: createConfig
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          description: Config data
          schema:
            $ref: '#/definitions/CreateConfigRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/VPNConfigResponse"
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        "503":
          description: Service Temporarily Unavailable
          schema:
            $ref: '#/definitions/ServiceTemporarilyUnavailable'

  /config/{config_id}:

    delete:
      security:
        - JWT:
          - manager
      summary: Delete VPN config
      operationId: deleteConfig
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: config_id
          required: true
          type: string
          description: Config ID
        - in: body
          name: body
          required: true
          description: Brigade ID
          schema:
            type: object
            required:
              - brigade_id
            properties:
              brigade_id:
                type: string
                format: uuid
                description: Brigade ID
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/FreeSlots"
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        "503":
          description: Service Temporarily Unavailable
          schema:
            $ref: '#/definitions/ServiceTemporarilyUnavailable'

  /brigade/{brigade_id}/slots:

    get:
      security:
        - JWT:
          - manager
      summary: Get VPN socket brigade slots stats
      operationId: getBrigadeSlots
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: brigade_id
          required: true
          type: string
          description: Brigade ID
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/BrigadeSlots"
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        "503":
          description: Service Temporarily Unavailable

  /brigade/{brigade_id}/activity:

    get:
      security:
        - JWT:
          - manager
      summary: Get VPN socket brigade activity stats
      operationId: getBrigadeActivity
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: brigade_id
          required: true
          type: string
          description: Brigade ID
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/BrigadeActivity"
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        "503":
          description: Service Temporarily Unavailable

definitions:
  
  Error:
    type: object
    properties:
      code:
        type: integer
        description: Error code
      message:
        type: string
        description: Error message

  ServiceTemporarilyUnavailable:
    type: object
    required:
      - message
      - retry_after
    properties:
      message:
        type: string
      retry_after:
        type: string
        format: date-time

  ConfigType:
    description: VPN config type
    type: string
    enum:
      - wireguard
      - outline
      - universal

  OutlineConfig:
    type: object
    required:
      - access_key
    properties:
      access_key:
        type: string
  
  AmneziaOVCConfig:
    type: object
    required:
      - tunnel_name
      - file_name
      - file_content
    properties:
      tunnel_name:
        type: string
      file_name:
        type: string
      file_content:
        type: string

  WireGuardConfig:
    type: object
    required:
      - tunnel_name
      - file_name
      - file_content
    properties:
      tunnel_name:
        type: string
      file_name:
        type: string
      file_content:
        type: string

  VPNGenConfig:
    type: object
    required:
      - access_key
    properties:
      access_key:
        type: string

  VPNConfig:
    type: object
    required:
      - user_id
      - name
      - domain
    properties:
      user_id:
        type: string
        format: uuid4
      name:
        type: string
      domain:
        type: string
      OutlineConfig:
        $ref: '#/definitions/OutlineConfig'
        x-omitempty: true
      AmneziaOVCConfig:
        $ref: '#/definitions/AmneziaOVCConfig'
        x-omitempty: true
      WireGuardConfig:
        $ref: '#/definitions/WireGuardConfig'
        x-omitempty: true
      VPNGenConfig:
        $ref: '#/definitions/VPNGenConfig'
        x-omitempty: true

  CreateConfigRequest:
    type: object
    required:
      - brigade_id
      - config_type
    properties:
      brigade_id:
        type: string
        format: uuid
        description: Brigade ID
      config_type:
        $ref: '#/definitions/ConfigType'

  BrigadeSlots:
    type: object
    required:
      - free_slots
      - total_slots
    properties:
      free_slots:
        type: integer
      total_slots:
        type: integer

  FreeSlots:
    type: object
    required:
      - free_slots
    properties:
      free_slots:
        type: integer

  VPNConfigResponse:
    type: object
    allOf:
      - $ref: '#/definitions/VPNConfig'
      - $ref: '#/definitions/FreeSlots'

  BrigadeActivity:
    type: object
    additionalProperties:
      $ref: '#/definitions/AcitivityData'

  AcitivityData:
    type: object
    required:
      - last_seen
      - updated
    properties:
      last_seen:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time

  Principal:
    type: object
    required:
      - scope
    properties:
      scope:
        type: array
        items:
          type: string

securityDefinitions:
  JWT:
    type: oauth2
    tokenUrl: /v1/token
    flow: application
    scopes:
      manager: Manager scope