// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for AmneziaOVCConfig

// register flags to command
func registerModelAmneziaOVCConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerAmneziaOVCConfigPropFileContent(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerAmneziaOVCConfigPropFileName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerAmneziaOVCConfigPropTunnelName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerAmneziaOVCConfigPropFileContent(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFileContentDescription := `Required. `

	var flagFileContentName string
	if cmdPrefix == "" {
		flagFileContentName = "file_content"
	} else {
		flagFileContentName = fmt.Sprintf("%v.file_content", cmdPrefix)
	}

	var flagFileContentDefault string

	_ = cmd.PersistentFlags().String(flagFileContentName, flagFileContentDefault, flagFileContentDescription)

	return nil
}

func registerAmneziaOVCConfigPropFileName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFileNameDescription := `Required. `

	var flagFileNameName string
	if cmdPrefix == "" {
		flagFileNameName = "file_name"
	} else {
		flagFileNameName = fmt.Sprintf("%v.file_name", cmdPrefix)
	}

	var flagFileNameDefault string

	_ = cmd.PersistentFlags().String(flagFileNameName, flagFileNameDefault, flagFileNameDescription)

	return nil
}

func registerAmneziaOVCConfigPropTunnelName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTunnelNameDescription := `Required. `

	var flagTunnelNameName string
	if cmdPrefix == "" {
		flagTunnelNameName = "tunnel_name"
	} else {
		flagTunnelNameName = fmt.Sprintf("%v.tunnel_name", cmdPrefix)
	}

	var flagTunnelNameDefault string

	_ = cmd.PersistentFlags().String(flagTunnelNameName, flagTunnelNameDefault, flagTunnelNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelAmneziaOVCConfigFlags(depth int, m *models.AmneziaOVCConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, FileContentAdded := retrieveAmneziaOVCConfigPropFileContentFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FileContentAdded

	err, FileNameAdded := retrieveAmneziaOVCConfigPropFileNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FileNameAdded

	err, TunnelNameAdded := retrieveAmneziaOVCConfigPropTunnelNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TunnelNameAdded

	return nil, retAdded
}

func retrieveAmneziaOVCConfigPropFileContentFlags(depth int, m *models.AmneziaOVCConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFileContentName := fmt.Sprintf("%v.file_content", cmdPrefix)
	if cmd.Flags().Changed(flagFileContentName) {

		var flagFileContentName string
		if cmdPrefix == "" {
			flagFileContentName = "file_content"
		} else {
			flagFileContentName = fmt.Sprintf("%v.file_content", cmdPrefix)
		}

		flagFileContentValue, err := cmd.Flags().GetString(flagFileContentName)
		if err != nil {
			return err, false
		}
		m.FileContent = &flagFileContentValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveAmneziaOVCConfigPropFileNameFlags(depth int, m *models.AmneziaOVCConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFileNameName := fmt.Sprintf("%v.file_name", cmdPrefix)
	if cmd.Flags().Changed(flagFileNameName) {

		var flagFileNameName string
		if cmdPrefix == "" {
			flagFileNameName = "file_name"
		} else {
			flagFileNameName = fmt.Sprintf("%v.file_name", cmdPrefix)
		}

		flagFileNameValue, err := cmd.Flags().GetString(flagFileNameName)
		if err != nil {
			return err, false
		}
		m.FileName = &flagFileNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveAmneziaOVCConfigPropTunnelNameFlags(depth int, m *models.AmneziaOVCConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTunnelNameName := fmt.Sprintf("%v.tunnel_name", cmdPrefix)
	if cmd.Flags().Changed(flagTunnelNameName) {

		var flagTunnelNameName string
		if cmdPrefix == "" {
			flagTunnelNameName = "tunnel_name"
		} else {
			flagTunnelNameName = fmt.Sprintf("%v.tunnel_name", cmdPrefix)
		}

		flagTunnelNameValue, err := cmd.Flags().GetString(flagTunnelNameName)
		if err != nil {
			return err, false
		}
		m.TunnelName = &flagTunnelNameValue

		retAdded = true
	}

	return nil, retAdded
}
