// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for CreateConfigRequest

// register flags to command
func registerModelCreateConfigRequestFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCreateConfigRequestPropBrigadeID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateConfigRequestPropConfigType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCreateConfigRequestPropBrigadeID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBrigadeIDDescription := `Required. Brigade ID`

	var flagBrigadeIDName string
	if cmdPrefix == "" {
		flagBrigadeIDName = "brigade_id"
	} else {
		flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBrigadeIDName, "", flagBrigadeIDDescription)

	return nil
}

func registerCreateConfigRequestPropConfigType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive config_type ConfigType is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCreateConfigRequestFlags(depth int, m *models.CreateConfigRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, BrigadeIDAdded := retrieveCreateConfigRequestPropBrigadeIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BrigadeIDAdded

	err, ConfigTypeAdded := retrieveCreateConfigRequestPropConfigTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ConfigTypeAdded

	return nil, retAdded
}

func retrieveCreateConfigRequestPropBrigadeIDFlags(depth int, m *models.CreateConfigRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBrigadeIDName := fmt.Sprintf("%v.brigade_id", cmdPrefix)
	if cmd.Flags().Changed(flagBrigadeIDName) {

		var flagBrigadeIDName string
		if cmdPrefix == "" {
			flagBrigadeIDName = "brigade_id"
		} else {
			flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
		}

		flagBrigadeIDValueStr, err := cmd.Flags().GetString(flagBrigadeIDName)
		if err != nil {
			return err, false
		}
		var flagBrigadeIDValue strfmt.UUID
		if err := flagBrigadeIDValue.UnmarshalText([]byte(flagBrigadeIDValueStr)); err != nil {
			return err, false
		}
		m.BrigadeID = &flagBrigadeIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateConfigRequestPropConfigTypeFlags(depth int, m *models.CreateConfigRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagConfigTypeName := fmt.Sprintf("%v.config_type", cmdPrefix)
	if cmd.Flags().Changed(flagConfigTypeName) {

		// warning: primitive config_type ConfigType is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}
