// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/client/operations"
)

// makeOperationOperationsDeleteConfigCmd returns a command to handle operation deleteConfig
func makeOperationOperationsDeleteConfigCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteConfig",
		Short: ``,
		RunE:  runOperationOperationsDeleteConfig,
	}

	if err := registerOperationOperationsDeleteConfigParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOperationsDeleteConfig uses cmd flags to call endpoint api
func runOperationOperationsDeleteConfig(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := operations.NewDeleteConfigParams()
	if err, _ = retrieveOperationOperationsDeleteConfigBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationOperationsDeleteConfigConfigIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOperationsDeleteConfigResult(appCli.Operations.DeleteConfig(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationOperationsDeleteConfigParamFlags registers all flags needed to fill params
func registerOperationOperationsDeleteConfigParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOperationsDeleteConfigBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationOperationsDeleteConfigConfigIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOperationsDeleteConfigBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. Brigade ID`)

	// add flags for body
	if err := registerModelDeleteConfigBodyFlags(0, "deleteConfigBody", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationOperationsDeleteConfigConfigIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagConfigIDDescription := `Required. Config ID`

	var flagConfigIDName string
	if cmdPrefix == "" {
		flagConfigIDName = "config_id"
	} else {
		flagConfigIDName = fmt.Sprintf("%v.config_id", cmdPrefix)
	}

	var flagConfigIDDefault string

	_ = cmd.PersistentFlags().String(flagConfigIDName, flagConfigIDDefault, flagConfigIDDescription)

	return nil
}

func retrieveOperationOperationsDeleteConfigBodyFlag(m *operations.DeleteConfigParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := operations.DeleteConfigBody{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in DeleteConfigBody: %v", err), false
		}
		m.Body = flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = operations.DeleteConfigBody{}
	}
	err, added := retrieveModelDeleteConfigBodyFlags(0, &flagBodyModel, "deleteConfigBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationOperationsDeleteConfigConfigIDFlag(m *operations.DeleteConfigParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("config_id") {

		var flagConfigIDName string
		if cmdPrefix == "" {
			flagConfigIDName = "config_id"
		} else {
			flagConfigIDName = fmt.Sprintf("%v.config_id", cmdPrefix)
		}

		flagConfigIDValue, err := cmd.Flags().GetString(flagConfigIDName)
		if err != nil {
			return err, false
		}
		m.ConfigID = flagConfigIDValue

	}

	return nil, retAdded
}

// parseOperationOperationsDeleteConfigResult parses request result and return the string content
func parseOperationOperationsDeleteConfigResult(resp0 *operations.DeleteConfigNoContent, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*operations.DeleteConfigNoContent)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*operations.DeleteConfigBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*operations.DeleteConfigUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*operations.DeleteConfigInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*operations.DeleteConfigServiceUnavailable)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelDeleteConfigBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerDeleteConfigBodyPropBrigadeID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerDeleteConfigBodyPropBrigadeID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBrigadeIDDescription := `Required. Brigade ID`

	var flagBrigadeIDName string
	if cmdPrefix == "" {
		flagBrigadeIDName = "brigade_id"
	} else {
		flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBrigadeIDName, "", flagBrigadeIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelDeleteConfigBodyFlags(depth int, m *operations.DeleteConfigBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, BrigadeIDAdded := retrieveDeleteConfigBodyPropBrigadeIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BrigadeIDAdded

	return nil, retAdded
}

func retrieveDeleteConfigBodyPropBrigadeIDFlags(depth int, m *operations.DeleteConfigBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBrigadeIDName := fmt.Sprintf("%v.brigade_id", cmdPrefix)
	if cmd.Flags().Changed(flagBrigadeIDName) {

		var flagBrigadeIDName string
		if cmdPrefix == "" {
			flagBrigadeIDName = "brigade_id"
		} else {
			flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
		}

		flagBrigadeIDValueStr, err := cmd.Flags().GetString(flagBrigadeIDName)
		if err != nil {
			return err, false
		}
		var flagBrigadeIDValue strfmt.UUID
		if err := flagBrigadeIDValue.UnmarshalText([]byte(flagBrigadeIDValueStr)); err != nil {
			return err, false
		}
		m.BrigadeID = &flagBrigadeIDValue

		retAdded = true
	}

	return nil, retAdded
}
