// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for FreeSlots

// register flags to command
func registerModelFreeSlotsFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerFreeSlotsPropFreeSlots(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerFreeSlotsPropFreeSlots(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFreeSlotsDescription := `Required. `

	var flagFreeSlotsName string
	if cmdPrefix == "" {
		flagFreeSlotsName = "free_slots"
	} else {
		flagFreeSlotsName = fmt.Sprintf("%v.free_slots", cmdPrefix)
	}

	var flagFreeSlotsDefault int64

	_ = cmd.PersistentFlags().Int64(flagFreeSlotsName, flagFreeSlotsDefault, flagFreeSlotsDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelFreeSlotsFlags(depth int, m *models.FreeSlots, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, FreeSlotsAdded := retrieveFreeSlotsPropFreeSlotsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FreeSlotsAdded

	return nil, retAdded
}

func retrieveFreeSlotsPropFreeSlotsFlags(depth int, m *models.FreeSlots, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFreeSlotsName := fmt.Sprintf("%v.free_slots", cmdPrefix)
	if cmd.Flags().Changed(flagFreeSlotsName) {

		var flagFreeSlotsName string
		if cmdPrefix == "" {
			flagFreeSlotsName = "free_slots"
		} else {
			flagFreeSlotsName = fmt.Sprintf("%v.free_slots", cmdPrefix)
		}

		flagFreeSlotsValue, err := cmd.Flags().GetInt64(flagFreeSlotsName)
		if err != nil {
			return err, false
		}
		m.FreeSlots = &flagFreeSlotsValue

		retAdded = true
	}

	return nil, retAdded
}
