// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/client/operations"
)

// makeOperationOperationsGetBrigadeActivityCmd returns a command to handle operation getBrigadeActivity
func makeOperationOperationsGetBrigadeActivityCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getBrigadeActivity",
		Short: ``,
		RunE:  runOperationOperationsGetBrigadeActivity,
	}

	if err := registerOperationOperationsGetBrigadeActivityParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOperationsGetBrigadeActivity uses cmd flags to call endpoint api
func runOperationOperationsGetBrigadeActivity(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := operations.NewGetBrigadeActivityParams()
	if err, _ = retrieveOperationOperationsGetBrigadeActivityBrigadeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOperationsGetBrigadeActivityResult(appCli.Operations.GetBrigadeActivity(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationOperationsGetBrigadeActivityParamFlags registers all flags needed to fill params
func registerOperationOperationsGetBrigadeActivityParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOperationsGetBrigadeActivityBrigadeIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOperationsGetBrigadeActivityBrigadeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagBrigadeIDDescription := `Required. Brigade ID`

	var flagBrigadeIDName string
	if cmdPrefix == "" {
		flagBrigadeIDName = "brigade_id"
	} else {
		flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
	}

	var flagBrigadeIDDefault string

	_ = cmd.PersistentFlags().String(flagBrigadeIDName, flagBrigadeIDDefault, flagBrigadeIDDescription)

	return nil
}

func retrieveOperationOperationsGetBrigadeActivityBrigadeIDFlag(m *operations.GetBrigadeActivityParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("brigade_id") {

		var flagBrigadeIDName string
		if cmdPrefix == "" {
			flagBrigadeIDName = "brigade_id"
		} else {
			flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
		}

		flagBrigadeIDValue, err := cmd.Flags().GetString(flagBrigadeIDName)
		if err != nil {
			return err, false
		}
		m.BrigadeID = flagBrigadeIDValue

	}

	return nil, retAdded
}

// parseOperationOperationsGetBrigadeActivityResult parses request result and return the string content
func parseOperationOperationsGetBrigadeActivityResult(resp0 *operations.GetBrigadeActivityOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*operations.GetBrigadeActivityOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*operations.GetBrigadeActivityBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*operations.GetBrigadeActivityUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*operations.GetBrigadeActivityInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getBrigadeActivityServiceUnavailable is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
