// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/client/operations"
)

// makeOperationOperationsGetBrigadeSlotsCmd returns a command to handle operation getBrigadeSlots
func makeOperationOperationsGetBrigadeSlotsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getBrigadeSlots",
		Short: ``,
		RunE:  runOperationOperationsGetBrigadeSlots,
	}

	if err := registerOperationOperationsGetBrigadeSlotsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOperationsGetBrigadeSlots uses cmd flags to call endpoint api
func runOperationOperationsGetBrigadeSlots(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := operations.NewGetBrigadeSlotsParams()
	if err, _ = retrieveOperationOperationsGetBrigadeSlotsBrigadeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOperationsGetBrigadeSlotsResult(appCli.Operations.GetBrigadeSlots(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationOperationsGetBrigadeSlotsParamFlags registers all flags needed to fill params
func registerOperationOperationsGetBrigadeSlotsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOperationsGetBrigadeSlotsBrigadeIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOperationsGetBrigadeSlotsBrigadeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagBrigadeIDDescription := `Required. Brigade ID`

	var flagBrigadeIDName string
	if cmdPrefix == "" {
		flagBrigadeIDName = "brigade_id"
	} else {
		flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
	}

	var flagBrigadeIDDefault string

	_ = cmd.PersistentFlags().String(flagBrigadeIDName, flagBrigadeIDDefault, flagBrigadeIDDescription)

	return nil
}

func retrieveOperationOperationsGetBrigadeSlotsBrigadeIDFlag(m *operations.GetBrigadeSlotsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("brigade_id") {

		var flagBrigadeIDName string
		if cmdPrefix == "" {
			flagBrigadeIDName = "brigade_id"
		} else {
			flagBrigadeIDName = fmt.Sprintf("%v.brigade_id", cmdPrefix)
		}

		flagBrigadeIDValue, err := cmd.Flags().GetString(flagBrigadeIDName)
		if err != nil {
			return err, false
		}
		m.BrigadeID = flagBrigadeIDValue

	}

	return nil, retAdded
}

// parseOperationOperationsGetBrigadeSlotsResult parses request result and return the string content
func parseOperationOperationsGetBrigadeSlotsResult(resp0 *operations.GetBrigadeSlotsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*operations.GetBrigadeSlotsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*operations.GetBrigadeSlotsBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*operations.GetBrigadeSlotsUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*operations.GetBrigadeSlotsInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getBrigadeSlotsServiceUnavailable is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
