// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for OutlineConfig

// register flags to command
func registerModelOutlineConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerOutlineConfigPropAccessKey(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerOutlineConfigPropAccessKey(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAccessKeyDescription := `Required. `

	var flagAccessKeyName string
	if cmdPrefix == "" {
		flagAccessKeyName = "access_key"
	} else {
		flagAccessKeyName = fmt.Sprintf("%v.access_key", cmdPrefix)
	}

	var flagAccessKeyDefault string

	_ = cmd.PersistentFlags().String(flagAccessKeyName, flagAccessKeyDefault, flagAccessKeyDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelOutlineConfigFlags(depth int, m *models.OutlineConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AccessKeyAdded := retrieveOutlineConfigPropAccessKeyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AccessKeyAdded

	return nil, retAdded
}

func retrieveOutlineConfigPropAccessKeyFlags(depth int, m *models.OutlineConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAccessKeyName := fmt.Sprintf("%v.access_key", cmdPrefix)
	if cmd.Flags().Changed(flagAccessKeyName) {

		var flagAccessKeyName string
		if cmdPrefix == "" {
			flagAccessKeyName = "access_key"
		} else {
			flagAccessKeyName = fmt.Sprintf("%v.access_key", cmdPrefix)
		}

		flagAccessKeyValue, err := cmd.Flags().GetString(flagAccessKeyName)
		if err != nil {
			return err, false
		}
		m.AccessKey = &flagAccessKeyValue

		retAdded = true
	}

	return nil, retAdded
}
