// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for Principal

// register flags to command
func registerModelPrincipalFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPrincipalPropScope(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPrincipalPropScope(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: scope []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPrincipalFlags(depth int, m *models.Principal, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ScopeAdded := retrievePrincipalPropScopeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ScopeAdded

	return nil, retAdded
}

func retrievePrincipalPropScopeFlags(depth int, m *models.Principal, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagScopeName := fmt.Sprintf("%v.scope", cmdPrefix)
	if cmd.Flags().Changed(flagScopeName) {
		// warning: scope array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
