// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for ServiceTemporarilyUnavailable

// register flags to command
func registerModelServiceTemporarilyUnavailableFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceTemporarilyUnavailablePropMessage(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceTemporarilyUnavailablePropRetryAfter(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceTemporarilyUnavailablePropMessage(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMessageDescription := `Required. `

	var flagMessageName string
	if cmdPrefix == "" {
		flagMessageName = "message"
	} else {
		flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
	}

	var flagMessageDefault string

	_ = cmd.PersistentFlags().String(flagMessageName, flagMessageDefault, flagMessageDescription)

	return nil
}

func registerServiceTemporarilyUnavailablePropRetryAfter(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRetryAfterDescription := `Required. `

	var flagRetryAfterName string
	if cmdPrefix == "" {
		flagRetryAfterName = "retry_after"
	} else {
		flagRetryAfterName = fmt.Sprintf("%v.retry_after", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagRetryAfterName, "", flagRetryAfterDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceTemporarilyUnavailableFlags(depth int, m *models.ServiceTemporarilyUnavailable, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, MessageAdded := retrieveServiceTemporarilyUnavailablePropMessageFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MessageAdded

	err, RetryAfterAdded := retrieveServiceTemporarilyUnavailablePropRetryAfterFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RetryAfterAdded

	return nil, retAdded
}

func retrieveServiceTemporarilyUnavailablePropMessageFlags(depth int, m *models.ServiceTemporarilyUnavailable, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMessageName := fmt.Sprintf("%v.message", cmdPrefix)
	if cmd.Flags().Changed(flagMessageName) {

		var flagMessageName string
		if cmdPrefix == "" {
			flagMessageName = "message"
		} else {
			flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
		}

		flagMessageValue, err := cmd.Flags().GetString(flagMessageName)
		if err != nil {
			return err, false
		}
		m.Message = &flagMessageValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceTemporarilyUnavailablePropRetryAfterFlags(depth int, m *models.ServiceTemporarilyUnavailable, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRetryAfterName := fmt.Sprintf("%v.retry_after", cmdPrefix)
	if cmd.Flags().Changed(flagRetryAfterName) {

		var flagRetryAfterName string
		if cmdPrefix == "" {
			flagRetryAfterName = "retry_after"
		} else {
			flagRetryAfterName = fmt.Sprintf("%v.retry_after", cmdPrefix)
		}

		flagRetryAfterValueStr, err := cmd.Flags().GetString(flagRetryAfterName)
		if err != nil {
			return err, false
		}
		var flagRetryAfterValue strfmt.DateTime
		if err := flagRetryAfterValue.UnmarshalText([]byte(flagRetryAfterValueStr)); err != nil {
			return err, false
		}
		m.RetryAfter = &flagRetryAfterValue

		retAdded = true
	}

	return nil, retAdded
}
