// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/spf13/cobra"
	"github.com/vpngen/dc-mgmt/api/vgsocket/gen-cli/models"
)

// Schema cli for VPNConfigResponse

// register flags to command
func registerModelVPNConfigResponseFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded VPNConfig flags

	if err := registerModelVPNConfigFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register embedded FreeSlots flags

	if err := registerModelFreeSlotsFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelVPNConfigResponseFlags(depth int, m *models.VPNConfigResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model VPNConfig
	err, AO0Added := retrieveModelVPNConfigFlags(depth, &m.VPNConfig, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO0Added

	// retrieve model FreeSlots
	err, AO1Added := retrieveModelFreeSlotsFlags(depth, &m.FreeSlots, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO1Added

	return nil, retAdded
}
